-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qaoa_kernel_expectation_cost_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_re_ce0 : OUT STD_LOGIC;
    state_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_im_ce0 : OUT STD_LOGIC;
    state_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    d_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_828_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_828_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_828_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
    grp_fu_828_p_ce : OUT STD_LOGIC );
end;


architecture behav of qaoa_kernel_expectation_cost_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal d_load_reg_204 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal d_load_1_reg_214 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal d_load_2_reg_224 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal d_load_3_reg_234 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal d_load_4_reg_244 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal d_load_5_reg_254 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal d_load_6_reg_264 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal d_load_7_reg_274 : STD_LOGIC_VECTOR (31 downto 0);
    signal d_load_8_reg_279 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_idle : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_ready : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_ce0 : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_ce0 : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out_ap_vld : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out_ap_vld : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce : STD_LOGIC;
    signal grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal d_ce0_local : STD_LOGIC;
    signal d_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_284_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component qaoa_kernel_expectation_cost_3_Pipeline_VITIS_LOOP_177_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_re_ce0 : OUT STD_LOGIC;
        state_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_im_ce0 : OUT STD_LOGIC;
        state_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_load_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        result_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        result_out_ap_vld : OUT STD_LOGIC;
        argmax_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        argmax_out_ap_vld : OUT STD_LOGIC;
        grp_fu_284_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_284_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_284_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
        grp_fu_284_p_ce : OUT STD_LOGIC );
    end component;


    component qaoa_kernel_mul_32s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;



begin
    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144 : component qaoa_kernel_expectation_cost_3_Pipeline_VITIS_LOOP_177_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start,
        ap_done => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done,
        ap_idle => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_idle,
        ap_ready => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_ready,
        state_re_address0 => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_address0,
        state_re_ce0 => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_ce0,
        state_re_q0 => state_re_q0,
        state_im_address0 => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_address0,
        state_im_ce0 => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_ce0,
        state_im_q0 => state_im_q0,
        d_load => d_load_reg_204,
        d_load_1 => d_load_1_reg_214,
        d_load_2 => d_load_2_reg_224,
        d_load_3 => d_load_3_reg_234,
        d_load_4 => d_load_4_reg_244,
        d_load_5 => d_load_5_reg_254,
        d_load_6 => d_load_6_reg_264,
        d_load_7 => d_load_7_reg_274,
        d_load_8 => d_load_8_reg_279,
        result_out => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out,
        result_out_ap_vld => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out_ap_vld,
        argmax_out => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out,
        argmax_out_ap_vld => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out_ap_vld,
        grp_fu_284_p_din0 => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din0,
        grp_fu_284_p_din1 => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din1,
        grp_fu_284_p_dout0 => grp_fu_828_p_dout0,
        grp_fu_284_p_ce => grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_ready = ap_const_logic_1)) then 
                    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                d_load_1_reg_214 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                d_load_2_reg_224 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                d_load_3_reg_234 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                d_load_4_reg_244 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                d_load_5_reg_254 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                d_load_6_reg_264 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                d_load_7_reg_274 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                d_load_8_reg_279 <= d_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                d_load_reg_204 <= d_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done, ap_CS_fsm_state11)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done)
    begin
        if ((grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out;
    ap_return_1 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out;
    d_address0 <= d_address0_local;

    d_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            d_address0_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            d_address0_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            d_address0_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            d_address0_local <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            d_address0_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            d_address0_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            d_address0_local <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            d_address0_local <= ap_const_lv64_1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            d_address0_local <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            d_address0_local <= "XXXX";
        end if; 
    end process;

    d_ce0 <= d_ce0_local;

    d_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            d_ce0_local <= ap_const_logic_1;
        else 
            d_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg;

    grp_fu_284_ce_assign_proc : process(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_284_ce <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce;
        else 
            grp_fu_284_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_828_p_ce <= grp_fu_284_ce;
    grp_fu_828_p_din0 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din0;
    grp_fu_828_p_din1 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din1;
    state_im_address0 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_address0;
    state_im_ce0 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_ce0;
    state_re_address0 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_address0;
    state_re_ce0 <= grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_ce0;
end behav;
