-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln128_1 : IN STD_LOGIC_VECTOR (2 downto 0);
    shl49 : IN STD_LOGIC_VECTOR (2 downto 0);
    mask : IN STD_LOGIC_VECTOR (8 downto 0);
    bufB_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufB_re_ce0 : OUT STD_LOGIC;
    bufB_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufB_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufB_re_ce1 : OUT STD_LOGIC;
    bufB_re_we1 : OUT STD_LOGIC;
    bufB_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bufB_re_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufB_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufB_im_ce0 : OUT STD_LOGIC;
    bufB_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufB_im_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufB_im_ce1 : OUT STD_LOGIC;
    bufB_im_we1 : OUT STD_LOGIC;
    bufB_im_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bufB_im_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufA_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufA_re_ce0 : OUT STD_LOGIC;
    bufA_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufA_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufA_re_ce1 : OUT STD_LOGIC;
    bufA_re_we1 : OUT STD_LOGIC;
    bufA_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bufA_re_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufA_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufA_im_ce0 : OUT STD_LOGIC;
    bufA_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bufA_im_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bufA_im_ce1 : OUT STD_LOGIC;
    bufA_im_we1 : OUT STD_LOGIC;
    bufA_im_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    bufA_im_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_cur_223131 : IN STD_LOGIC_VECTOR (0 downto 0);
    trunc_ln102_cast : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln127 : IN STD_LOGIC_VECTOR (21 downto 0);
    state_next_222129 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_917_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_917_p_din1 : OUT STD_LOGIC_VECTOR (21 downto 0);
    grp_fu_917_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
    grp_fu_917_p_ce : OUT STD_LOGIC );
end;


architecture behav of qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln140_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal state_next_222129_read_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_cur_223131_read_read_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln127_cast_fu_252_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln127_cast_reg_481 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln102_cast_cast_fu_256_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln102_cast_cast_reg_489 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln140_reg_497 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln140_fu_278_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln140_reg_501 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln144_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_reg_506 : STD_LOGIC_VECTOR (0 downto 0);
    signal bufB_re_addr_reg_510 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufB_im_addr_reg_515 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufB_re_addr_1_reg_520 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufB_im_addr_1_reg_526 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufA_re_addr_reg_532 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufA_im_addr_reg_537 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufA_re_addr_1_reg_542 : STD_LOGIC_VECTOR (8 downto 0);
    signal bufA_im_addr_1_reg_548 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln56_fu_354_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln56_reg_554 : STD_LOGIC_VECTOR (51 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln56_1_fu_359_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln56_1_reg_560 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln56_2_fu_364_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln56_2_reg_566 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln56_3_fu_369_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln56_3_reg_572 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln140_fu_284_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln147_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal s_idx_fu_70 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_s_idx_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal bufB_re_ce1_local : STD_LOGIC;
    signal bufB_re_address1_local : STD_LOGIC_VECTOR (8 downto 0);
    signal bufB_re_ce0_local : STD_LOGIC;
    signal bufB_re_we1_local : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bufB_re_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln62_fu_400_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln59_fu_442_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bufB_im_ce1_local : STD_LOGIC;
    signal bufB_im_address1_local : STD_LOGIC_VECTOR (8 downto 0);
    signal bufB_im_ce0_local : STD_LOGIC;
    signal bufB_im_we1_local : STD_LOGIC;
    signal bufB_im_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln62_1_fu_408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln59_1_fu_450_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bufA_re_ce1_local : STD_LOGIC;
    signal bufA_re_address1_local : STD_LOGIC_VECTOR (8 downto 0);
    signal bufA_re_ce0_local : STD_LOGIC;
    signal bufA_re_we1_local : STD_LOGIC;
    signal bufA_re_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal bufA_im_ce1_local : STD_LOGIC;
    signal bufA_im_address1_local : STD_LOGIC_VECTOR (8 downto 0);
    signal bufA_im_ce0_local : STD_LOGIC;
    signal bufA_im_we1_local : STD_LOGIC;
    signal bufA_im_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_216_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_216_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_220_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_220_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_224_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_224_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_228_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_228_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_228_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln141_fu_292_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln128_1_cast_fu_260_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln141_fu_296_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal slice_fu_302_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s_flip_fu_312_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_58_fu_333_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_59_fu_340_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_326_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_im_fu_347_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_220_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_fu_224_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal sub_ln56_fu_384_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_fu_232_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln56_2_fu_390_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln56_1_fu_374_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_242_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln56_1_fu_416_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln56_6_fu_432_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln56_5_fu_422_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_228 : BOOLEAN;
    signal ap_condition_181 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component qaoa_kernel_mul_32s_22s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component qaoa_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_22s_52_2_1_U41 : component qaoa_kernel_mul_32s_22s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 22,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_220_p0,
        din1 => grp_fu_220_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_220_p2);

    mul_32s_22s_52_2_1_U42 : component qaoa_kernel_mul_32s_22s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 22,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_224_p0,
        din1 => grp_fu_224_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_224_p2);

    mul_32s_22s_52_2_1_U43 : component qaoa_kernel_mul_32s_22s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 22,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_228_p0,
        din1 => grp_fu_228_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_228_p2);

    flow_control_loop_pipe_sequential_init_U : component qaoa_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    s_idx_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                s_idx_fu_70 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
                s_idx_fu_70 <= add_ln140_reg_501;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln140_reg_501 <= add_ln140_fu_278_p2;
                bufA_im_addr_1_reg_548 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
                bufA_im_addr_reg_537 <= zext_ln140_fu_284_p1(9 - 1 downto 0);
                bufA_re_addr_1_reg_542 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
                bufA_re_addr_reg_532 <= zext_ln140_fu_284_p1(9 - 1 downto 0);
                bufB_im_addr_1_reg_526 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
                bufB_im_addr_reg_515 <= zext_ln140_fu_284_p1(9 - 1 downto 0);
                bufB_re_addr_1_reg_520 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
                bufB_re_addr_reg_510 <= zext_ln140_fu_284_p1(9 - 1 downto 0);
                icmp_ln140_reg_497 <= icmp_ln140_fu_272_p2;
                icmp_ln144_reg_506 <= icmp_ln144_fu_306_p2;
                sext_ln127_cast_reg_481 <= sext_ln127_cast_fu_252_p1;
                trunc_ln102_cast_cast_reg_489 <= trunc_ln102_cast_cast_fu_256_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                sext_ln56_1_reg_560 <= sext_ln56_1_fu_359_p1;
                sext_ln56_2_reg_566 <= sext_ln56_2_fu_364_p1;
                sext_ln56_3_reg_572 <= sext_ln56_3_fu_369_p1;
                sext_ln56_reg_554 <= sext_ln56_fu_354_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln140_fu_272_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln140_fu_272_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln140_fu_278_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_s_idx_1) + unsigned(ap_const_lv10_1));
    add_ln59_1_fu_450_p2 <= std_logic_vector(unsigned(grp_fu_242_p4) + unsigned(trunc_ln56_5_fu_422_p4));
    add_ln59_fu_442_p2 <= std_logic_vector(unsigned(grp_fu_232_p4) + unsigned(trunc_ln56_6_fu_432_p4));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_181_assign_proc : process(state_next_222129_read_reg_469, icmp_ln140_reg_497, icmp_ln144_reg_506)
    begin
                ap_condition_181 <= ((state_next_222129_read_reg_469 = ap_const_lv1_1) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0));
    end process;


    ap_condition_228_assign_proc : process(state_next_222129_read_reg_469, icmp_ln140_reg_497, icmp_ln144_reg_506)
    begin
                ap_condition_228 <= ((state_next_222129_read_reg_469 = ap_const_lv1_0) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln140_fu_272_p2)
    begin
        if (((icmp_ln140_fu_272_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_s_idx_1_assign_proc : process(ap_CS_fsm_state1, s_idx_fu_70, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_s_idx_1 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_s_idx_1 <= s_idx_fu_70;
        end if; 
    end process;

    b_im_fu_347_p3 <= 
        bufB_im_q0 when (state_cur_223131(0) = '1') else 
        bufA_im_q0;
    bufA_im_address0 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
    bufA_im_address1 <= bufA_im_address1_local;

    bufA_im_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, bufA_im_addr_reg_537, bufA_im_addr_1_reg_548, zext_ln140_fu_284_p1, ap_CS_fsm_state3)
    begin
        if (((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufA_im_address1_local <= bufA_im_addr_1_reg_548;
        elsif (((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufA_im_address1_local <= bufA_im_addr_reg_537;
        elsif (((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_0) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1))) then 
            bufA_im_address1_local <= zext_ln140_fu_284_p1(9 - 1 downto 0);
        else 
            bufA_im_address1_local <= "XXXXXXXXX";
        end if; 
    end process;

    bufA_im_ce0 <= bufA_im_ce0_local;

    bufA_im_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bufA_im_ce0_local <= ap_const_logic_1;
        else 
            bufA_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bufA_im_ce1 <= bufA_im_ce1_local;

    bufA_im_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_0) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1)))) then 
            bufA_im_ce1_local <= ap_const_logic_1;
        else 
            bufA_im_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufA_im_d1 <= bufA_im_d1_local;

    bufA_im_d1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3, sub_ln62_1_fu_408_p2, add_ln59_1_fu_450_p2, ap_condition_228)
    begin
        if ((ap_const_boolean_1 = ap_condition_228)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                bufA_im_d1_local <= add_ln59_1_fu_450_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                bufA_im_d1_local <= sub_ln62_1_fu_408_p2;
            else 
                bufA_im_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            bufA_im_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bufA_im_we1 <= bufA_im_we1_local;

    bufA_im_we1_local_assign_proc : process(ap_CS_fsm_state4, state_next_222129_read_reg_469, icmp_ln140_reg_497, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)))) then 
            bufA_im_we1_local <= ap_const_logic_1;
        else 
            bufA_im_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufA_re_address0 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
    bufA_re_address1 <= bufA_re_address1_local;

    bufA_re_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, bufA_re_addr_reg_532, bufA_re_addr_1_reg_542, zext_ln140_fu_284_p1, ap_CS_fsm_state3)
    begin
        if (((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufA_re_address1_local <= bufA_re_addr_1_reg_542;
        elsif (((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufA_re_address1_local <= bufA_re_addr_reg_532;
        elsif (((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_0) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1))) then 
            bufA_re_address1_local <= zext_ln140_fu_284_p1(9 - 1 downto 0);
        else 
            bufA_re_address1_local <= "XXXXXXXXX";
        end if; 
    end process;

    bufA_re_ce0 <= bufA_re_ce0_local;

    bufA_re_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bufA_re_ce0_local <= ap_const_logic_1;
        else 
            bufA_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bufA_re_ce1 <= bufA_re_ce1_local;

    bufA_re_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_0) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1)))) then 
            bufA_re_ce1_local <= ap_const_logic_1;
        else 
            bufA_re_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufA_re_d1 <= bufA_re_d1_local;

    bufA_re_d1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3, sub_ln62_fu_400_p2, add_ln59_fu_442_p2, ap_condition_228)
    begin
        if ((ap_const_boolean_1 = ap_condition_228)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                bufA_re_d1_local <= add_ln59_fu_442_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                bufA_re_d1_local <= sub_ln62_fu_400_p2;
            else 
                bufA_re_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            bufA_re_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bufA_re_we1 <= bufA_re_we1_local;

    bufA_re_we1_local_assign_proc : process(ap_CS_fsm_state4, state_next_222129_read_reg_469, icmp_ln140_reg_497, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)))) then 
            bufA_re_we1_local <= ap_const_logic_1;
        else 
            bufA_re_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufB_im_address0 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
    bufB_im_address1 <= bufB_im_address1_local;

    bufB_im_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, bufB_im_addr_reg_515, bufB_im_addr_1_reg_526, zext_ln140_fu_284_p1, ap_CS_fsm_state3)
    begin
        if (((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufB_im_address1_local <= bufB_im_addr_1_reg_526;
        elsif (((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufB_im_address1_local <= bufB_im_addr_reg_515;
        elsif (((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_1) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1))) then 
            bufB_im_address1_local <= zext_ln140_fu_284_p1(9 - 1 downto 0);
        else 
            bufB_im_address1_local <= "XXXXXXXXX";
        end if; 
    end process;

    bufB_im_ce0 <= bufB_im_ce0_local;

    bufB_im_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bufB_im_ce0_local <= ap_const_logic_1;
        else 
            bufB_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bufB_im_ce1 <= bufB_im_ce1_local;

    bufB_im_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_1) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1)))) then 
            bufB_im_ce1_local <= ap_const_logic_1;
        else 
            bufB_im_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufB_im_d1 <= bufB_im_d1_local;

    bufB_im_d1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3, sub_ln62_1_fu_408_p2, add_ln59_1_fu_450_p2, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                bufB_im_d1_local <= add_ln59_1_fu_450_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                bufB_im_d1_local <= sub_ln62_1_fu_408_p2;
            else 
                bufB_im_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            bufB_im_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bufB_im_we1 <= bufB_im_we1_local;

    bufB_im_we1_local_assign_proc : process(ap_CS_fsm_state4, state_next_222129_read_reg_469, icmp_ln140_reg_497, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)))) then 
            bufB_im_we1_local <= ap_const_logic_1;
        else 
            bufB_im_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufB_re_address0 <= zext_ln147_fu_318_p1(9 - 1 downto 0);
    bufB_re_address1 <= bufB_re_address1_local;

    bufB_re_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, bufB_re_addr_reg_510, bufB_re_addr_1_reg_520, zext_ln140_fu_284_p1, ap_CS_fsm_state3)
    begin
        if (((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufB_re_address1_local <= bufB_re_addr_1_reg_520;
        elsif (((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0))) then 
            bufB_re_address1_local <= bufB_re_addr_reg_510;
        elsif (((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_1) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1))) then 
            bufB_re_address1_local <= zext_ln140_fu_284_p1(9 - 1 downto 0);
        else 
            bufB_re_address1_local <= "XXXXXXXXX";
        end if; 
    end process;

    bufB_re_ce0 <= bufB_re_ce0_local;

    bufB_re_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bufB_re_ce0_local <= ap_const_logic_1;
        else 
            bufB_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bufB_re_ce1 <= bufB_re_ce1_local;

    bufB_re_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln140_fu_272_p2, ap_CS_fsm_state4, state_next_222129_read_reg_469, state_cur_223131_read_read_fu_92_p2, icmp_ln140_reg_497, icmp_ln144_fu_306_p2, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_cur_223131_read_read_fu_92_p2 = ap_const_lv1_1) and (icmp_ln140_fu_272_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln144_fu_306_p2 = ap_const_lv1_1)))) then 
            bufB_re_ce1_local <= ap_const_logic_1;
        else 
            bufB_re_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bufB_re_d1 <= bufB_re_d1_local;

    bufB_re_d1_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3, sub_ln62_fu_400_p2, add_ln59_fu_442_p2, ap_condition_181)
    begin
        if ((ap_const_boolean_1 = ap_condition_181)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                bufB_re_d1_local <= add_ln59_fu_442_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                bufB_re_d1_local <= sub_ln62_fu_400_p2;
            else 
                bufB_re_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            bufB_re_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    bufB_re_we1 <= bufB_re_we1_local;

    bufB_re_we1_local_assign_proc : process(ap_CS_fsm_state4, state_next_222129_read_reg_469, icmp_ln140_reg_497, icmp_ln144_reg_506, ap_CS_fsm_state3)
    begin
        if ((((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)) or ((state_next_222129_read_reg_469 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln144_reg_506 = ap_const_lv1_1) and (icmp_ln140_reg_497 = ap_const_lv1_0)))) then 
            bufB_re_we1_local <= ap_const_logic_1;
        else 
            bufB_re_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_58_fu_333_p3 <= 
        bufB_re_q1 when (state_cur_223131(0) = '1') else 
        bufA_re_q1;
    empty_59_fu_340_p3 <= 
        bufB_im_q1 when (state_cur_223131(0) = '1') else 
        bufA_im_q1;
    empty_fu_326_p3 <= 
        bufB_re_q0 when (state_cur_223131(0) = '1') else 
        bufA_re_q0;

    grp_fu_216_p0_assign_proc : process(sext_ln56_fu_354_p1, ap_CS_fsm_state2, sext_ln56_1_reg_560, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_216_p0 <= sext_ln56_1_reg_560(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_216_p0 <= sext_ln56_fu_354_p1(32 - 1 downto 0);
        else 
            grp_fu_216_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_216_p1_assign_proc : process(sext_ln127_cast_reg_481, trunc_ln102_cast_cast_reg_489, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_216_p1 <= sext_ln127_cast_reg_481(22 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_216_p1 <= trunc_ln102_cast_cast_reg_489(22 - 1 downto 0);
        else 
            grp_fu_216_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_220_p0_assign_proc : process(sext_ln56_reg_554, ap_CS_fsm_state2, sext_ln56_1_fu_359_p1, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_220_p0 <= sext_ln56_reg_554(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_220_p0 <= sext_ln56_1_fu_359_p1(32 - 1 downto 0);
        else 
            grp_fu_220_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_220_p1_assign_proc : process(sext_ln127_cast_reg_481, trunc_ln102_cast_cast_reg_489, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_220_p1 <= sext_ln127_cast_reg_481(22 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_220_p1 <= trunc_ln102_cast_cast_reg_489(22 - 1 downto 0);
        else 
            grp_fu_220_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_224_p0_assign_proc : process(ap_CS_fsm_state2, sext_ln56_2_reg_566, sext_ln56_3_fu_369_p1, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_224_p0 <= sext_ln56_2_reg_566(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_224_p0 <= sext_ln56_3_fu_369_p1(32 - 1 downto 0);
        else 
            grp_fu_224_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_224_p1_assign_proc : process(sext_ln127_cast_reg_481, trunc_ln102_cast_cast_reg_489, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_224_p1 <= trunc_ln102_cast_cast_reg_489(22 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_224_p1 <= sext_ln127_cast_reg_481(22 - 1 downto 0);
        else 
            grp_fu_224_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_228_p0_assign_proc : process(ap_CS_fsm_state2, sext_ln56_2_fu_364_p1, sext_ln56_3_reg_572, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_228_p0 <= sext_ln56_3_reg_572(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_228_p0 <= sext_ln56_2_fu_364_p1(32 - 1 downto 0);
        else 
            grp_fu_228_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_228_p1_assign_proc : process(sext_ln127_cast_reg_481, trunc_ln102_cast_cast_reg_489, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_228_p1 <= trunc_ln102_cast_cast_reg_489(22 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_228_p1 <= sext_ln127_cast_reg_481(22 - 1 downto 0);
        else 
            grp_fu_228_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_232_p4 <= grp_fu_917_p_dout0(51 downto 20);
    grp_fu_242_p4 <= grp_fu_228_p2(51 downto 20);
    grp_fu_917_p_ce <= ap_const_logic_1;
    grp_fu_917_p_din0 <= grp_fu_216_p0;
    grp_fu_917_p_din1 <= grp_fu_216_p1;
    icmp_ln140_fu_272_p2 <= "1" when (ap_sig_allocacmp_s_idx_1 = ap_const_lv10_200) else "0";
    icmp_ln144_fu_306_p2 <= "1" when (slice_fu_302_p1 = shl49) else "0";
    lshr_ln141_fu_296_p2 <= std_logic_vector(shift_right(unsigned(trunc_ln141_fu_292_p1),to_integer(unsigned('0' & zext_ln128_1_cast_fu_260_p1(9-1 downto 0)))));
    s_flip_fu_312_p2 <= (trunc_ln141_fu_292_p1 xor mask);
        sext_ln127_cast_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln127),52));

        sext_ln56_1_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_59_fu_340_p3),52));

        sext_ln56_2_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_fu_326_p3),52));

        sext_ln56_3_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(b_im_fu_347_p3),52));

        sext_ln56_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_58_fu_333_p3),52));

    slice_fu_302_p1 <= lshr_ln141_fu_296_p2(3 - 1 downto 0);
    state_cur_223131_read_read_fu_92_p2 <= state_cur_223131;
    state_next_222129_read_reg_469 <= state_next_222129;
    sub_ln56_1_fu_416_p2 <= std_logic_vector(unsigned(ap_const_lv52_0) - unsigned(grp_fu_220_p2));
    sub_ln56_fu_384_p2 <= std_logic_vector(unsigned(ap_const_lv52_0) - unsigned(grp_fu_224_p2));
    sub_ln62_1_fu_408_p2 <= std_logic_vector(unsigned(trunc_ln56_1_fu_374_p4) - unsigned(grp_fu_242_p4));
    sub_ln62_fu_400_p2 <= std_logic_vector(unsigned(grp_fu_232_p4) - unsigned(trunc_ln56_2_fu_390_p4));
        trunc_ln102_cast_cast_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln102_cast),52));

    trunc_ln141_fu_292_p1 <= ap_sig_allocacmp_s_idx_1(9 - 1 downto 0);
    trunc_ln56_1_fu_374_p4 <= grp_fu_220_p2(51 downto 20);
    trunc_ln56_2_fu_390_p4 <= sub_ln56_fu_384_p2(51 downto 20);
    trunc_ln56_5_fu_422_p4 <= sub_ln56_1_fu_416_p2(51 downto 20);
    trunc_ln56_6_fu_432_p4 <= grp_fu_224_p2(51 downto 20);
    zext_ln128_1_cast_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln128_1),9));
    zext_ln140_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_s_idx_1),64));
    zext_ln147_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(s_flip_fu_312_p2),64));
end behav;
