-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qaoa_kernel_qaoaStep_hls_3_1_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_re_ce0 : OUT STD_LOGIC;
    state_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_re_ce1 : OUT STD_LOGIC;
    state_re_we1 : OUT STD_LOGIC;
    state_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    state_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_im_ce0 : OUT STD_LOGIC;
    state_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_im_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_im_ce1 : OUT STD_LOGIC;
    state_im_we1 : OUT STD_LOGIC;
    state_im_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    d_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    gamma_0_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    beta_0_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_828_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_828_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_828_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
    grp_fu_828_p_ce : OUT STD_LOGIC );
end;


architecture behav of qaoa_kernel_qaoaStep_hls_3_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_build_feasible_superposition_3_s_fu_58_ap_start : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_ap_done : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_ap_idle : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_ap_ready : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_state_re_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_build_feasible_superposition_3_s_fu_58_state_re_ce1 : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_state_re_we1 : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_state_re_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_build_feasible_superposition_3_s_fu_58_state_im_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_build_feasible_superposition_3_s_fu_58_state_im_ce1 : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_state_im_we1 : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_state_im_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_ap_start : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_ap_done : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_ap_idle : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_ap_ready : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_state_re_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_state_re_ce0 : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_state_re_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_state_re_ce1 : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_state_re_we1 : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_state_re_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_state_im_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_state_im_ce0 : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_d_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_d_ce0 : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce : STD_LOGIC;
    signal grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_ap_start : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_ap_done : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_ap_idle : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_ap_ready : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_re_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_state_re_ce0 : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_re_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_state_re_ce1 : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_re_we1 : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_re_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_state_im_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_state_im_ce0 : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_im_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_state_im_ce1 : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_im_we1 : STD_LOGIC;
    signal grp_applyMixer_hls_3_s_fu_80_state_im_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce : STD_LOGIC;
    signal grp_build_feasible_superposition_3_s_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_applyCost_hls_3_s_fu_66_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_applyMixer_hls_3_s_fu_80_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_102_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_fu_102_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_102_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_102_ce : STD_LOGIC;
    signal grp_fu_106_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component qaoa_kernel_build_feasible_superposition_3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_re_ce1 : OUT STD_LOGIC;
        state_re_we1 : OUT STD_LOGIC;
        state_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        state_im_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_im_ce1 : OUT STD_LOGIC;
        state_im_we1 : OUT STD_LOGIC;
        state_im_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component qaoa_kernel_applyCost_hls_3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_re_ce0 : OUT STD_LOGIC;
        state_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_re_ce1 : OUT STD_LOGIC;
        state_re_we1 : OUT STD_LOGIC;
        state_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        state_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_im_ce0 : OUT STD_LOGIC;
        state_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        d_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        d_ce0 : OUT STD_LOGIC;
        d_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        gamma : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_102_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_102_p_din1 : OUT STD_LOGIC_VECTOR (21 downto 0);
        grp_fu_102_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
        grp_fu_102_p_ce : OUT STD_LOGIC;
        grp_fu_106_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_106_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_106_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
        grp_fu_106_p_ce : OUT STD_LOGIC );
    end component;


    component qaoa_kernel_applyMixer_hls_3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_re_ce0 : OUT STD_LOGIC;
        state_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_re_ce1 : OUT STD_LOGIC;
        state_re_we1 : OUT STD_LOGIC;
        state_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        state_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_im_ce0 : OUT STD_LOGIC;
        state_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        state_im_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        state_im_ce1 : OUT STD_LOGIC;
        state_im_we1 : OUT STD_LOGIC;
        state_im_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        beta : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_102_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_102_p_din1 : OUT STD_LOGIC_VECTOR (21 downto 0);
        grp_fu_102_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
        grp_fu_102_p_ce : OUT STD_LOGIC );
    end component;


    component qaoa_kernel_mul_32s_22s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component qaoa_kernel_mul_32s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;



begin
    grp_build_feasible_superposition_3_s_fu_58 : component qaoa_kernel_build_feasible_superposition_3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_build_feasible_superposition_3_s_fu_58_ap_start,
        ap_done => grp_build_feasible_superposition_3_s_fu_58_ap_done,
        ap_idle => grp_build_feasible_superposition_3_s_fu_58_ap_idle,
        ap_ready => grp_build_feasible_superposition_3_s_fu_58_ap_ready,
        state_re_address1 => grp_build_feasible_superposition_3_s_fu_58_state_re_address1,
        state_re_ce1 => grp_build_feasible_superposition_3_s_fu_58_state_re_ce1,
        state_re_we1 => grp_build_feasible_superposition_3_s_fu_58_state_re_we1,
        state_re_d1 => grp_build_feasible_superposition_3_s_fu_58_state_re_d1,
        state_im_address1 => grp_build_feasible_superposition_3_s_fu_58_state_im_address1,
        state_im_ce1 => grp_build_feasible_superposition_3_s_fu_58_state_im_ce1,
        state_im_we1 => grp_build_feasible_superposition_3_s_fu_58_state_im_we1,
        state_im_d1 => grp_build_feasible_superposition_3_s_fu_58_state_im_d1);

    grp_applyCost_hls_3_s_fu_66 : component qaoa_kernel_applyCost_hls_3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_applyCost_hls_3_s_fu_66_ap_start,
        ap_done => grp_applyCost_hls_3_s_fu_66_ap_done,
        ap_idle => grp_applyCost_hls_3_s_fu_66_ap_idle,
        ap_ready => grp_applyCost_hls_3_s_fu_66_ap_ready,
        state_re_address0 => grp_applyCost_hls_3_s_fu_66_state_re_address0,
        state_re_ce0 => grp_applyCost_hls_3_s_fu_66_state_re_ce0,
        state_re_q0 => state_re_q0,
        state_re_address1 => grp_applyCost_hls_3_s_fu_66_state_re_address1,
        state_re_ce1 => grp_applyCost_hls_3_s_fu_66_state_re_ce1,
        state_re_we1 => grp_applyCost_hls_3_s_fu_66_state_re_we1,
        state_re_d1 => grp_applyCost_hls_3_s_fu_66_state_re_d1,
        state_im_address0 => grp_applyCost_hls_3_s_fu_66_state_im_address0,
        state_im_ce0 => grp_applyCost_hls_3_s_fu_66_state_im_ce0,
        state_im_q0 => state_im_q0,
        d_address0 => grp_applyCost_hls_3_s_fu_66_d_address0,
        d_ce0 => grp_applyCost_hls_3_s_fu_66_d_ce0,
        d_q0 => d_q0,
        gamma => gamma_0_0_val,
        grp_fu_102_p_din0 => grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0,
        grp_fu_102_p_din1 => grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1,
        grp_fu_102_p_dout0 => grp_fu_102_p2,
        grp_fu_102_p_ce => grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce,
        grp_fu_106_p_din0 => grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din0,
        grp_fu_106_p_din1 => grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din1,
        grp_fu_106_p_dout0 => grp_fu_828_p_dout0,
        grp_fu_106_p_ce => grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce);

    grp_applyMixer_hls_3_s_fu_80 : component qaoa_kernel_applyMixer_hls_3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_applyMixer_hls_3_s_fu_80_ap_start,
        ap_done => grp_applyMixer_hls_3_s_fu_80_ap_done,
        ap_idle => grp_applyMixer_hls_3_s_fu_80_ap_idle,
        ap_ready => grp_applyMixer_hls_3_s_fu_80_ap_ready,
        state_re_address0 => grp_applyMixer_hls_3_s_fu_80_state_re_address0,
        state_re_ce0 => grp_applyMixer_hls_3_s_fu_80_state_re_ce0,
        state_re_q0 => state_re_q0,
        state_re_address1 => grp_applyMixer_hls_3_s_fu_80_state_re_address1,
        state_re_ce1 => grp_applyMixer_hls_3_s_fu_80_state_re_ce1,
        state_re_we1 => grp_applyMixer_hls_3_s_fu_80_state_re_we1,
        state_re_d1 => grp_applyMixer_hls_3_s_fu_80_state_re_d1,
        state_im_address0 => grp_applyMixer_hls_3_s_fu_80_state_im_address0,
        state_im_ce0 => grp_applyMixer_hls_3_s_fu_80_state_im_ce0,
        state_im_q0 => state_im_q0,
        state_im_address1 => grp_applyMixer_hls_3_s_fu_80_state_im_address1,
        state_im_ce1 => grp_applyMixer_hls_3_s_fu_80_state_im_ce1,
        state_im_we1 => grp_applyMixer_hls_3_s_fu_80_state_im_we1,
        state_im_d1 => grp_applyMixer_hls_3_s_fu_80_state_im_d1,
        beta => beta_0_0_val,
        grp_fu_102_p_din0 => grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0,
        grp_fu_102_p_din1 => grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1,
        grp_fu_102_p_dout0 => grp_fu_102_p2,
        grp_fu_102_p_ce => grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce);

    mul_32s_22s_52_2_1_U74 : component qaoa_kernel_mul_32s_22s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 22,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_102_p0,
        din1 => grp_fu_102_p1,
        ce => grp_fu_102_ce,
        dout => grp_fu_102_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_applyCost_hls_3_s_fu_66_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_applyCost_hls_3_s_fu_66_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_applyCost_hls_3_s_fu_66_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_applyCost_hls_3_s_fu_66_ap_ready = ap_const_logic_1)) then 
                    grp_applyCost_hls_3_s_fu_66_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_applyMixer_hls_3_s_fu_80_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_applyMixer_hls_3_s_fu_80_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_applyMixer_hls_3_s_fu_80_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_applyMixer_hls_3_s_fu_80_ap_ready = ap_const_logic_1)) then 
                    grp_applyMixer_hls_3_s_fu_80_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_build_feasible_superposition_3_s_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_build_feasible_superposition_3_s_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_build_feasible_superposition_3_s_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_build_feasible_superposition_3_s_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_build_feasible_superposition_3_s_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_build_feasible_superposition_3_s_fu_58_ap_done, grp_applyCost_hls_3_s_fu_66_ap_done, grp_applyMixer_hls_3_s_fu_80_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_build_feasible_superposition_3_s_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_applyCost_hls_3_s_fu_66_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_applyMixer_hls_3_s_fu_80_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_ap_done)
    begin
        if ((grp_build_feasible_superposition_3_s_fu_58_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_applyCost_hls_3_s_fu_66_ap_done)
    begin
        if ((grp_applyCost_hls_3_s_fu_66_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_applyMixer_hls_3_s_fu_80_ap_done)
    begin
        if ((grp_applyMixer_hls_3_s_fu_80_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_applyMixer_hls_3_s_fu_80_ap_done, ap_CS_fsm_state6)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_applyMixer_hls_3_s_fu_80_ap_done = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_applyMixer_hls_3_s_fu_80_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_applyMixer_hls_3_s_fu_80_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    d_address0 <= grp_applyCost_hls_3_s_fu_66_d_address0;
    d_ce0 <= grp_applyCost_hls_3_s_fu_66_d_ce0;
    grp_applyCost_hls_3_s_fu_66_ap_start <= grp_applyCost_hls_3_s_fu_66_ap_start_reg;
    grp_applyMixer_hls_3_s_fu_80_ap_start <= grp_applyMixer_hls_3_s_fu_80_ap_start_reg;
    grp_build_feasible_superposition_3_s_fu_58_ap_start <= grp_build_feasible_superposition_3_s_fu_58_ap_start_reg;

    grp_fu_102_ce_assign_proc : process(grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce, grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_102_ce <= grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_102_ce <= grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce;
        else 
            grp_fu_102_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_102_p0_assign_proc : process(grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0, grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_102_p0 <= grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_102_p0 <= grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0;
        else 
            grp_fu_102_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_102_p1_assign_proc : process(grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1, grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_102_p1 <= grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_102_p1 <= grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1;
        else 
            grp_fu_102_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_106_ce_assign_proc : process(grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_106_ce <= grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce;
        else 
            grp_fu_106_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_828_p_ce <= grp_fu_106_ce;
    grp_fu_828_p_din0 <= grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din0;
    grp_fu_828_p_din1 <= grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din1;

    state_im_address0_assign_proc : process(grp_applyCost_hls_3_s_fu_66_state_im_address0, grp_applyMixer_hls_3_s_fu_80_state_im_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_im_address0 <= grp_applyMixer_hls_3_s_fu_80_state_im_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_im_address0 <= grp_applyCost_hls_3_s_fu_66_state_im_address0;
        else 
            state_im_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    state_im_address1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_im_address1, grp_applyMixer_hls_3_s_fu_80_state_im_address1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_im_address1 <= grp_applyMixer_hls_3_s_fu_80_state_im_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_im_address1 <= grp_build_feasible_superposition_3_s_fu_58_state_im_address1;
        else 
            state_im_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    state_im_ce0_assign_proc : process(grp_applyCost_hls_3_s_fu_66_state_im_ce0, grp_applyMixer_hls_3_s_fu_80_state_im_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_im_ce0 <= grp_applyMixer_hls_3_s_fu_80_state_im_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_im_ce0 <= grp_applyCost_hls_3_s_fu_66_state_im_ce0;
        else 
            state_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    state_im_ce1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_im_ce1, grp_applyMixer_hls_3_s_fu_80_state_im_ce1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_im_ce1 <= grp_applyMixer_hls_3_s_fu_80_state_im_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_im_ce1 <= grp_build_feasible_superposition_3_s_fu_58_state_im_ce1;
        else 
            state_im_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    state_im_d1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_im_d1, grp_applyMixer_hls_3_s_fu_80_state_im_d1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_im_d1 <= grp_applyMixer_hls_3_s_fu_80_state_im_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_im_d1 <= grp_build_feasible_superposition_3_s_fu_58_state_im_d1;
        else 
            state_im_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    state_im_we1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_im_we1, grp_applyMixer_hls_3_s_fu_80_state_im_we1, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_im_we1 <= grp_applyMixer_hls_3_s_fu_80_state_im_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_im_we1 <= grp_build_feasible_superposition_3_s_fu_58_state_im_we1;
        else 
            state_im_we1 <= ap_const_logic_0;
        end if; 
    end process;


    state_re_address0_assign_proc : process(grp_applyCost_hls_3_s_fu_66_state_re_address0, grp_applyMixer_hls_3_s_fu_80_state_re_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_re_address0 <= grp_applyMixer_hls_3_s_fu_80_state_re_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_re_address0 <= grp_applyCost_hls_3_s_fu_66_state_re_address0;
        else 
            state_re_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    state_re_address1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_re_address1, grp_applyCost_hls_3_s_fu_66_state_re_address1, grp_applyMixer_hls_3_s_fu_80_state_re_address1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_re_address1 <= grp_applyMixer_hls_3_s_fu_80_state_re_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_re_address1 <= grp_applyCost_hls_3_s_fu_66_state_re_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_re_address1 <= grp_build_feasible_superposition_3_s_fu_58_state_re_address1;
        else 
            state_re_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    state_re_ce0_assign_proc : process(grp_applyCost_hls_3_s_fu_66_state_re_ce0, grp_applyMixer_hls_3_s_fu_80_state_re_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_re_ce0 <= grp_applyMixer_hls_3_s_fu_80_state_re_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_re_ce0 <= grp_applyCost_hls_3_s_fu_66_state_re_ce0;
        else 
            state_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    state_re_ce1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_re_ce1, grp_applyCost_hls_3_s_fu_66_state_re_ce1, grp_applyMixer_hls_3_s_fu_80_state_re_ce1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_re_ce1 <= grp_applyMixer_hls_3_s_fu_80_state_re_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_re_ce1 <= grp_applyCost_hls_3_s_fu_66_state_re_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_re_ce1 <= grp_build_feasible_superposition_3_s_fu_58_state_re_ce1;
        else 
            state_re_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    state_re_d1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_re_d1, grp_applyCost_hls_3_s_fu_66_state_re_d1, grp_applyMixer_hls_3_s_fu_80_state_re_d1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_re_d1 <= grp_applyMixer_hls_3_s_fu_80_state_re_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_re_d1 <= grp_applyCost_hls_3_s_fu_66_state_re_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_re_d1 <= grp_build_feasible_superposition_3_s_fu_58_state_re_d1;
        else 
            state_re_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    state_re_we1_assign_proc : process(grp_build_feasible_superposition_3_s_fu_58_state_re_we1, grp_applyCost_hls_3_s_fu_66_state_re_we1, grp_applyMixer_hls_3_s_fu_80_state_re_we1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            state_re_we1 <= grp_applyMixer_hls_3_s_fu_80_state_re_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            state_re_we1 <= grp_applyCost_hls_3_s_fu_66_state_re_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            state_re_we1 <= grp_build_feasible_superposition_3_s_fu_58_state_re_we1;
        else 
            state_re_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
