-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qaoa_kernel_applyCost_hls_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_re_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_re_ce0 : OUT STD_LOGIC;
    state_re_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    state_re_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_re_ce1 : OUT STD_LOGIC;
    state_re_we1 : OUT STD_LOGIC;
    state_re_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    state_im_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    state_im_ce0 : OUT STD_LOGIC;
    state_im_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    d_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    d_ce0 : OUT STD_LOGIC;
    d_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    gamma : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_102_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_102_p_din1 : OUT STD_LOGIC_VECTOR (21 downto 0);
    grp_fu_102_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
    grp_fu_102_p_ce : OUT STD_LOGIC;
    grp_fu_106_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_106_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_106_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
    grp_fu_106_p_ce : OUT STD_LOGIC );
end;


architecture behav of qaoa_kernel_applyCost_hls_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv34_0 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    constant ap_const_lv34_4DBA76D4 : STD_LOGIC_VECTOR (33 downto 0) := "0001001101101110100111011011010100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv34_DBC09578 : STD_LOGIC_VECTOR (33 downto 0) := "0011011011110000001001010101111000";
    constant ap_const_lv76_145F306DC9C8 : STD_LOGIC_VECTOR (75 downto 0) := "0000000000000000000000000000000101000101111100110000011011011100100111001000";
    constant ap_const_lv15_4400 : STD_LOGIC_VECTOR (14 downto 0) := "100010000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv34_1921FB544 : STD_LOGIC_VECTOR (33 downto 0) := "0110010010000111111011010101000100";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage8 : signal is "none";
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln86_reg_828 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage8 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal cordic_apfixed_circ_table_arctan_128_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal cordic_apfixed_circ_table_arctan_128_q0 : STD_LOGIC_VECTOR (125 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln86_fu_234_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln86_reg_823 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln86_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_reg_828_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_832 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln61_reg_832_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_832_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_832_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_301_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln86_reg_838 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln86_reg_838_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln86_reg_838_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln86_reg_838_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln86_3_fu_309_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln86_3_reg_845 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln86_3_reg_845_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln86_3_reg_845_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln86_3_reg_845_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln61_1_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_850 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_850_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_850_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_850_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_1_reg_850_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_costHamiltonian_3_s_fu_209_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal Hs_reg_854 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001_ignoreCallOp112 : BOOLEAN;
    signal sext_ln88_fu_344_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal select_ln86_2_fu_351_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln86_2_reg_864 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ang_reg_870 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln71_fu_368_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln71_reg_877 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_s_fu_371_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_s_reg_882 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln86_1_fu_380_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln86_1_reg_888 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal sign0_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sign0_reg_894 : STD_LOGIC_VECTOR (0 downto 0);
    signal inabs_fu_397_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inabs_reg_899 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln42_fu_404_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln42_reg_904 : STD_LOGIC_VECTOR (20 downto 0);
    signal y_s_fu_408_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal y_s_reg_909 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal first_iter_0_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_920 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_925 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_reg_930 : STD_LOGIC_VECTOR (1 downto 0);
    signal this_re_reg_943 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_73_reg_959 : STD_LOGIC_VECTOR (30 downto 0);
    signal this_re_load_reg_964 : STD_LOGIC_VECTOR (31 downto 0);
    signal this_im_load_reg_969 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_216_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln42_reg_974 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal icmp_ln225_2_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln225_2_reg_979 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal select_ln61_fu_552_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln61_reg_985 : STD_LOGIC_VECTOR (33 downto 0);
    signal d_1_fu_559_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_1_reg_991 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_583_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_reg_996 : STD_LOGIC_VECTOR (33 downto 0);
    signal y_fu_591_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal y_reg_1001 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln61_fu_599_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln61_reg_1006 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln61_2_fu_603_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln61_2_reg_1012 : STD_LOGIC_VECTOR (32 downto 0);
    signal outcos_reg_1018 : STD_LOGIC_VECTOR (21 downto 0);
    signal outsin_fu_731_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal outsin_reg_1023 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln65_fu_751_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln65_1_fu_755_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal mul_ln65_reg_1038 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln65_2_fu_759_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln65_3_fu_763_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal mul_ln65_1_reg_1053 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_costHamiltonian_3_s_fu_209_ap_start : STD_LOGIC;
    signal grp_costHamiltonian_3_s_fu_209_ap_done : STD_LOGIC;
    signal grp_costHamiltonian_3_s_fu_209_ap_idle : STD_LOGIC;
    signal grp_costHamiltonian_3_s_fu_209_ap_ready : STD_LOGIC;
    signal grp_costHamiltonian_3_s_fu_209_s : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_costHamiltonian_3_s_fu_209_d_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_costHamiltonian_3_s_fu_209_d_ce0 : STD_LOGIC;
    signal grp_costHamiltonian_3_s_fu_209_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_ignoreCallOp78 : BOOLEAN;
    signal ap_block_pp0_stage2_ignoreCallOp84 : BOOLEAN;
    signal ap_block_pp0_stage3_ignoreCallOp85 : BOOLEAN;
    signal ap_block_pp0_stage4_ignoreCallOp86 : BOOLEAN;
    signal ap_block_pp0_stage5_ignoreCallOp87 : BOOLEAN;
    signal ap_block_pp0_stage6_ignoreCallOp88 : BOOLEAN;
    signal ap_block_pp0_stage6_ignoreCallOp97 : BOOLEAN;
    signal ap_block_pp0_stage7_ignoreCallOp98 : BOOLEAN;
    signal ap_block_pp0_stage8_ignoreCallOp99 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp100 : BOOLEAN;
    signal ap_block_pp0_stage1_ignoreCallOp101 : BOOLEAN;
    signal zext_ln61_fu_447_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln86_fu_442_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_136 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal z_fu_620_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal empty_61_fu_140 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal empty_62_fu_144 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal n_fu_148 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln61_fu_322_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal s_fu_152 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal indvar_flatten_fu_156 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln86_1_fu_272_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (14 downto 0);
    signal cordic_apfixed_circ_table_arctan_128_ce0_local : STD_LOGIC;
    signal state_re_ce0_local : STD_LOGIC;
    signal state_re_we1_local : STD_LOGIC;
    signal ap_block_pp0_stage8_11001 : BOOLEAN;
    signal ap_block_pp0_stage8 : BOOLEAN;
    signal state_re_ce1_local : STD_LOGIC;
    signal state_im_ce0_local : STD_LOGIC;
    signal grp_fu_216_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_216_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_221_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_221_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal grp_fu_226_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_226_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal add_ln86_fu_289_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln211_fu_392_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_221_p2 : STD_LOGIC_VECTOR (75 downto 0);
    signal shl_ln_fu_468_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln42_fu_475_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_fu_480_p4 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln42_2_fu_490_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln225_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln228_fu_494_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_72_fu_526_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln225_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_516_p4 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_85_cast_fu_536_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal empty_63_fu_540_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln61_fu_548_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln76_fu_567_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln81_fu_575_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln77_fu_571_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln82_fu_579_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln73_fu_607_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln78_fu_610_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln83_fu_615_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln248_2_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln248_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln248_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln261_fu_627_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal outsin_0_in_in_i_fu_660_p7 : STD_LOGIC_VECTOR (32 downto 0);
    signal outsin_0_in_in_i_fu_660_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln254_fu_632_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal outcos_write_assign_in_in_i_fu_686_p7 : STD_LOGIC_VECTOR (32 downto 0);
    signal outcos_write_assign_in_in_i_fu_686_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal outcos_write_assign_in_in_i_fu_686_p9 : STD_LOGIC_VECTOR (32 downto 0);
    signal outsin_0_in_in_i_fu_660_p9 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln7_fu_715_p4 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln266_fu_725_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln65_fu_767_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_216_p00 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_221_p00 : STD_LOGIC_VECTOR (75 downto 0);
    signal outsin_0_in_in_i_fu_660_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal outsin_0_in_in_i_fu_660_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal outsin_0_in_in_i_fu_660_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal outcos_write_assign_in_in_i_fu_686_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal outcos_write_assign_in_in_i_fu_686_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal outcos_write_assign_in_in_i_fu_686_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component qaoa_kernel_costHamiltonian_3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (8 downto 0);
        d_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        d_ce0 : OUT STD_LOGIC;
        d_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component qaoa_kernel_mul_11ns_33ns_34_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (32 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component qaoa_kernel_mul_32ns_46ns_76_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (45 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (75 downto 0) );
    end component;


    component qaoa_kernel_mul_32s_22s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component qaoa_kernel_mul_32s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component qaoa_kernel_sparsemux_7_2_33_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (32 downto 0);
        din1 : IN STD_LOGIC_VECTOR (32 downto 0);
        din2 : IN STD_LOGIC_VECTOR (32 downto 0);
        def : IN STD_LOGIC_VECTOR (32 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component qaoa_kernel_applyCost_hls_3_s_cordic_apfixed_circ_table_arctan_128_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (125 downto 0) );
    end component;


    component qaoa_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    cordic_apfixed_circ_table_arctan_128_U : component qaoa_kernel_applyCost_hls_3_s_cordic_apfixed_circ_table_arctan_128_ROM_AUTO_1R
    generic map (
        DataWidth => 126,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => cordic_apfixed_circ_table_arctan_128_address0,
        ce0 => cordic_apfixed_circ_table_arctan_128_ce0_local,
        q0 => cordic_apfixed_circ_table_arctan_128_q0);

    grp_costHamiltonian_3_s_fu_209 : component qaoa_kernel_costHamiltonian_3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_costHamiltonian_3_s_fu_209_ap_start,
        ap_done => grp_costHamiltonian_3_s_fu_209_ap_done,
        ap_idle => grp_costHamiltonian_3_s_fu_209_ap_idle,
        ap_ready => grp_costHamiltonian_3_s_fu_209_ap_ready,
        s => grp_costHamiltonian_3_s_fu_209_s,
        d_address0 => grp_costHamiltonian_3_s_fu_209_d_address0,
        d_ce0 => grp_costHamiltonian_3_s_fu_209_d_ce0,
        d_q0 => d_q0,
        ap_return => grp_costHamiltonian_3_s_fu_209_ap_return);

    mul_11ns_33ns_34_2_1_U9 : component qaoa_kernel_mul_11ns_33ns_34_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 11,
        din1_WIDTH => 33,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_216_p0,
        din1 => grp_fu_216_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_216_p2);

    mul_32ns_46ns_76_3_1_U10 : component qaoa_kernel_mul_32ns_46ns_76_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 46,
        dout_WIDTH => 76)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_221_p0,
        din1 => grp_fu_221_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_221_p2);

    sparsemux_7_2_33_1_1_U13 : component qaoa_kernel_sparsemux_7_2_33_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 33,
        CASE1 => "01",
        din1_WIDTH => 33,
        CASE2 => "00",
        din2_WIDTH => 33,
        def_WIDTH => 33,
        sel_WIDTH => 2,
        dout_WIDTH => 33)
    port map (
        din0 => sub_ln261_fu_627_p2,
        din1 => trunc_ln61_reg_1006,
        din2 => sub_ln261_fu_627_p2,
        def => outsin_0_in_in_i_fu_660_p7,
        sel => outsin_0_in_in_i_fu_660_p8,
        dout => outsin_0_in_in_i_fu_660_p9);

    sparsemux_7_2_33_1_1_U14 : component qaoa_kernel_sparsemux_7_2_33_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 33,
        CASE1 => "01",
        din1_WIDTH => 33,
        CASE2 => "00",
        din2_WIDTH => 33,
        def_WIDTH => 33,
        sel_WIDTH => 2,
        dout_WIDTH => 33)
    port map (
        din0 => sub_ln254_fu_632_p2,
        din1 => sub_ln254_fu_632_p2,
        din2 => trunc_ln61_2_reg_1012,
        def => outcos_write_assign_in_in_i_fu_686_p7,
        sel => outcos_write_assign_in_in_i_fu_686_p8,
        dout => outcos_write_assign_in_in_i_fu_686_p9);

    flow_control_loop_pipe_sequential_init_U : component qaoa_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage8,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage8)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    grp_costHamiltonian_3_s_fu_209_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_costHamiltonian_3_s_fu_209_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln86_fu_266_p2 = ap_const_lv1_0))) then 
                    grp_costHamiltonian_3_s_fu_209_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_costHamiltonian_3_s_fu_209_ap_ready = ap_const_logic_1)) then 
                    grp_costHamiltonian_3_s_fu_209_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    empty_61_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                empty_61_fu_140 <= ap_const_lv34_4DBA76D4;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                empty_61_fu_140 <= x_reg_996;
            end if; 
        end if;
    end process;

    empty_62_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                empty_62_fu_144 <= ap_const_lv34_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                empty_62_fu_144 <= y_reg_1001;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln86_fu_266_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_156 <= add_ln86_1_fu_272_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_156 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    n_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                n_fu_148 <= ap_const_lv6_0;
            elsif (((icmp_ln86_reg_828 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                n_fu_148 <= add_ln61_fu_322_p2;
            end if; 
        end if;
    end process;

    s_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                s_fu_152 <= ap_const_lv10_0;
            elsif (((icmp_ln86_reg_828 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                s_fu_152 <= select_ln86_3_fu_309_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001_ignoreCallOp112) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                Hs_reg_854 <= grp_costHamiltonian_3_s_fu_209_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                ang_reg_870 <= grp_fu_106_p_dout0(51 downto 20);
                select_ln86_2_reg_864 <= select_ln86_2_fu_351_p3;
                x_s_reg_882 <= x_s_fu_371_p2;
                    zext_ln71_reg_877(5 downto 0) <= zext_ln71_fu_368_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage8_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                d_1_reg_991 <= select_ln61_fu_552_p3(33 downto 33);
                icmp_ln225_2_reg_979 <= icmp_ln225_2_fu_505_p2;
                select_ln61_reg_985 <= select_ln61_fu_552_p3;
                trunc_ln61_2_reg_1012 <= trunc_ln61_2_fu_603_p1;
                trunc_ln61_reg_1006 <= trunc_ln61_fu_599_p1;
                x_reg_996 <= x_fu_583_p3;
                y_reg_1001 <= y_fu_591_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                empty_fu_136 <= z_fu_620_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                first_iter_0_reg_920 <= first_iter_0_fu_417_p2;
                icmp_ln86_reg_828 <= icmp_ln86_fu_266_p2;
                icmp_ln86_reg_828_pp0_iter1_reg <= icmp_ln86_reg_828;
                k_reg_930 <= grp_fu_221_p2(66 downto 65);
                sext_ln86_reg_823 <= sext_ln86_fu_234_p1;
                this_re_reg_943 <= zext_ln86_fu_442_p1(9 - 1 downto 0);
                tmp_reg_925 <= grp_fu_221_p2(75 downto 65);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln61_1_reg_850 <= icmp_ln61_1_fu_328_p2;
                icmp_ln61_1_reg_850_pp0_iter1_reg <= icmp_ln61_1_reg_850;
                icmp_ln61_1_reg_850_pp0_iter2_reg <= icmp_ln61_1_reg_850_pp0_iter1_reg;
                icmp_ln61_1_reg_850_pp0_iter3_reg <= icmp_ln61_1_reg_850_pp0_iter2_reg;
                icmp_ln61_1_reg_850_pp0_iter4_reg <= icmp_ln61_1_reg_850_pp0_iter3_reg;
                icmp_ln61_reg_832 <= icmp_ln61_fu_295_p2;
                icmp_ln61_reg_832_pp0_iter1_reg <= icmp_ln61_reg_832;
                icmp_ln61_reg_832_pp0_iter2_reg <= icmp_ln61_reg_832_pp0_iter1_reg;
                icmp_ln61_reg_832_pp0_iter3_reg <= icmp_ln61_reg_832_pp0_iter2_reg;
                select_ln86_3_reg_845 <= select_ln86_3_fu_309_p3;
                select_ln86_3_reg_845_pp0_iter1_reg <= select_ln86_3_reg_845;
                select_ln86_3_reg_845_pp0_iter2_reg <= select_ln86_3_reg_845_pp0_iter1_reg;
                select_ln86_3_reg_845_pp0_iter3_reg <= select_ln86_3_reg_845_pp0_iter2_reg;
                select_ln86_reg_838 <= select_ln86_fu_301_p3;
                select_ln86_reg_838_pp0_iter1_reg <= select_ln86_reg_838;
                select_ln86_reg_838_pp0_iter2_reg <= select_ln86_reg_838_pp0_iter1_reg;
                select_ln86_reg_838_pp0_iter3_reg <= select_ln86_reg_838_pp0_iter2_reg;
                this_im_load_reg_969 <= state_im_q0;
                tmp_73_reg_959 <= cordic_apfixed_circ_table_arctan_128_q0(125 downto 95);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                inabs_reg_899 <= inabs_fu_397_p3;
                select_ln86_1_reg_888 <= select_ln86_1_fu_380_p3;
                sign0_reg_894 <= sign0_fu_387_p2;
                trunc_ln42_reg_904 <= trunc_ln42_fu_404_p1;
                y_s_reg_909 <= y_s_fu_408_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_ln42_reg_974 <= grp_fu_216_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                mul_ln65_1_reg_1053 <= grp_fu_102_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                mul_ln65_reg_1038 <= grp_fu_102_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                outcos_reg_1018 <= outcos_write_assign_in_in_i_fu_686_p9(32 downto 11);
                outsin_reg_1023 <= outsin_fu_731_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                this_re_load_reg_964 <= state_re_q0;
            end if;
        end if;
    end process;
    zext_ln71_reg_877(33 downto 6) <= "0000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage8_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to4, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln42_fu_475_p2 <= std_logic_vector(unsigned(shl_ln_fu_468_p3) + unsigned(mul_ln42_reg_974));
    add_ln61_fu_322_p2 <= std_logic_vector(unsigned(select_ln86_fu_301_p3) + unsigned(ap_const_lv6_1));
    add_ln65_fu_767_p2 <= std_logic_vector(unsigned(mul_ln65_reg_1038) + unsigned(mul_ln65_1_reg_1053));
    add_ln76_fu_567_p2 <= std_logic_vector(unsigned(select_ln86_2_reg_864) + unsigned(y_s_reg_909));
    add_ln78_fu_610_p2 <= std_logic_vector(unsigned(zext_ln73_fu_607_p1) + unsigned(select_ln61_reg_985));
    add_ln82_fu_579_p2 <= std_logic_vector(unsigned(x_s_reg_882) + unsigned(select_ln86_1_reg_888));
    add_ln86_1_fu_272_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv15_1));
    add_ln86_fu_289_p2 <= std_logic_vector(unsigned(s_fu_152) + unsigned(ap_const_lv10_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
    ap_CS_fsm_pp0_stage8 <= ap_CS_fsm(8);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp100 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_ignoreCallOp101 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_ignoreCallOp78 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_ignoreCallOp84 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001_ignoreCallOp112 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_ignoreCallOp85 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_ignoreCallOp86 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_ignoreCallOp87 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_ignoreCallOp88 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_ignoreCallOp97 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_ignoreCallOp98 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_ignoreCallOp99 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage8_assign_proc : process(ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln86_reg_828)
    begin
        if (((icmp_ln86_reg_828 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
            ap_condition_exit_pp0_iter0_stage8 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage8 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage8;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage8_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_156)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_156;
        end if; 
    end process;

    cordic_apfixed_circ_table_arctan_128_address0 <= zext_ln61_fu_447_p1(7 - 1 downto 0);

    cordic_apfixed_circ_table_arctan_128_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cordic_apfixed_circ_table_arctan_128_ce0_local <= ap_const_logic_1;
        else 
            cordic_apfixed_circ_table_arctan_128_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    d_1_fu_559_p3 <= select_ln61_fu_552_p3(33 downto 33);
    d_address0 <= grp_costHamiltonian_3_s_fu_209_d_address0;
    d_ce0 <= grp_costHamiltonian_3_s_fu_209_d_ce0;
    empty_63_fu_540_p3 <= 
        tmp_s_fu_516_p4 when (or_ln225_fu_510_p2(0) = '1') else 
        tmp_85_cast_fu_536_p1;
    first_iter_0_fu_417_p2 <= "1" when (select_ln86_reg_838_pp0_iter3_reg = ap_const_lv6_0) else "0";
    grp_costHamiltonian_3_s_fu_209_ap_start <= grp_costHamiltonian_3_s_fu_209_ap_start_reg;
    grp_costHamiltonian_3_s_fu_209_s <= select_ln86_3_fu_309_p3(9 - 1 downto 0);
    grp_fu_102_p_ce <= ap_const_logic_1;
    grp_fu_102_p_din0 <= grp_fu_226_p0;
    grp_fu_102_p_din1 <= grp_fu_226_p1;
    grp_fu_106_p_ce <= ap_const_logic_1;
    grp_fu_106_p_din0 <= sext_ln88_fu_344_p1(32 - 1 downto 0);
    grp_fu_106_p_din1 <= sext_ln86_reg_823(32 - 1 downto 0);
    grp_fu_216_p0 <= grp_fu_216_p00(11 - 1 downto 0);
    grp_fu_216_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_925),34));
    grp_fu_216_p1 <= ap_const_lv34_DBC09578(33 - 1 downto 0);
    grp_fu_221_p0 <= grp_fu_221_p00(32 - 1 downto 0);
    grp_fu_221_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(inabs_reg_899),76));
    grp_fu_221_p1 <= ap_const_lv76_145F306DC9C8(46 - 1 downto 0);

    grp_fu_226_p0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, sext_ln65_fu_751_p1, sext_ln65_3_fu_763_p1, ap_block_pp0_stage5, ap_block_pp0_stage6)
    begin
        if ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                grp_fu_226_p0 <= sext_ln65_3_fu_763_p1(32 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                grp_fu_226_p0 <= sext_ln65_fu_751_p1(32 - 1 downto 0);
            else 
                grp_fu_226_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_226_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_226_p1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, sext_ln65_1_fu_755_p1, sext_ln65_2_fu_759_p1, ap_block_pp0_stage5, ap_block_pp0_stage6)
    begin
        if ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                grp_fu_226_p1 <= sext_ln65_2_fu_759_p1(22 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                grp_fu_226_p1 <= sext_ln65_1_fu_755_p1(22 - 1 downto 0);
            else 
                grp_fu_226_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_226_p1 <= "XXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln225_2_fu_505_p2 <= "1" when (k_reg_930 = ap_const_lv2_1) else "0";
    icmp_ln225_fu_500_p2 <= "1" when (k_reg_930 = ap_const_lv2_3) else "0";
    icmp_ln248_2_fu_642_p2 <= "1" when (k_reg_930 = ap_const_lv2_0) else "0";
    icmp_ln248_fu_637_p2 <= "1" when (k_reg_930 = ap_const_lv2_2) else "0";
    icmp_ln61_1_fu_328_p2 <= "1" when (add_ln61_fu_322_p2 = ap_const_lv6_22) else "0";
    icmp_ln61_fu_295_p2 <= "1" when (n_fu_148 = ap_const_lv6_22) else "0";
    icmp_ln86_fu_266_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv15_4400) else "0";
    inabs_fu_397_p3 <= 
        ang_reg_870 when (sign0_fu_387_p2(0) = '1') else 
        sub_ln211_fu_392_p2;
    or_ln225_fu_510_p2 <= (icmp_ln225_fu_500_p2 or icmp_ln225_2_fu_505_p2);
    or_ln248_fu_647_p2 <= (icmp_ln248_2_fu_642_p2 or icmp_ln225_2_reg_979);
    outcos_write_assign_in_in_i_fu_686_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    outcos_write_assign_in_in_i_fu_686_p8 <= (icmp_ln248_fu_637_p2 & icmp_ln225_2_reg_979);
    outsin_0_in_in_i_fu_660_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    outsin_0_in_in_i_fu_660_p8 <= (icmp_ln248_fu_637_p2 & or_ln248_fu_647_p2);
    outsin_fu_731_p3 <= 
        trunc_ln7_fu_715_p4 when (sign0_reg_894(0) = '1') else 
        sub_ln266_fu_725_p2;
    r_fu_480_p4 <= add_ln42_fu_475_p2(33 downto 1);
    select_ln61_fu_552_p3 <= 
        sext_ln61_fu_548_p1 when (first_iter_0_reg_920(0) = '1') else 
        empty_fu_136;
    select_ln86_1_fu_380_p3 <= 
        ap_const_lv34_0 when (icmp_ln61_reg_832_pp0_iter3_reg(0) = '1') else 
        empty_62_fu_144;
    select_ln86_2_fu_351_p3 <= 
        ap_const_lv34_4DBA76D4 when (icmp_ln61_reg_832_pp0_iter3_reg(0) = '1') else 
        empty_61_fu_140;
    select_ln86_3_fu_309_p3 <= 
        add_ln86_fu_289_p2 when (icmp_ln61_fu_295_p2(0) = '1') else 
        s_fu_152;
    select_ln86_fu_301_p3 <= 
        ap_const_lv6_0 when (icmp_ln61_fu_295_p2(0) = '1') else 
        n_fu_148;
        sext_ln61_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_63_fu_540_p3),34));

        sext_ln65_1_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(outcos_reg_1018),52));

        sext_ln65_2_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(outsin_reg_1023),52));

        sext_ln65_3_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(this_im_load_reg_969),52));

        sext_ln65_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(this_re_load_reg_964),52));

        sext_ln86_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gamma),52));

        sext_ln88_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Hs_reg_854),52));

    shl_ln_fu_468_p3 <= (trunc_ln42_reg_904 & ap_const_lv13_0);
    sign0_fu_387_p2 <= "1" when (signed(ang_reg_870) > signed(ap_const_lv32_0)) else "0";
    state_im_address0 <= zext_ln86_fu_442_p1(9 - 1 downto 0);
    state_im_ce0 <= state_im_ce0_local;

    state_im_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            state_im_ce0_local <= ap_const_logic_1;
        else 
            state_im_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    state_re_address0 <= zext_ln86_fu_442_p1(9 - 1 downto 0);
    state_re_address1 <= this_re_reg_943;
    state_re_ce0 <= state_re_ce0_local;

    state_re_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            state_re_ce0_local <= ap_const_logic_1;
        else 
            state_re_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    state_re_ce1 <= state_re_ce1_local;

    state_re_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage8, ap_block_pp0_stage8_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage8_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8))) then 
            state_re_ce1_local <= ap_const_logic_1;
        else 
            state_re_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    state_re_d1 <= add_ln65_fu_767_p2(51 downto 20);
    state_re_we1 <= state_re_we1_local;

    state_re_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage8, icmp_ln61_1_reg_850_pp0_iter4_reg, ap_block_pp0_stage8_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage8_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage8) and (icmp_ln61_1_reg_850_pp0_iter4_reg = ap_const_lv1_1))) then 
            state_re_we1_local <= ap_const_logic_1;
        else 
            state_re_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln211_fu_392_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(ang_reg_870));
    sub_ln228_fu_494_p2 <= std_logic_vector(unsigned(ap_const_lv34_1921FB544) - unsigned(zext_ln42_2_fu_490_p1));
    sub_ln254_fu_632_p2 <= std_logic_vector(unsigned(ap_const_lv33_0) - unsigned(trunc_ln61_2_reg_1012));
    sub_ln261_fu_627_p2 <= std_logic_vector(unsigned(ap_const_lv33_0) - unsigned(trunc_ln61_reg_1006));
    sub_ln266_fu_725_p2 <= std_logic_vector(unsigned(ap_const_lv22_0) - unsigned(trunc_ln7_fu_715_p4));
    sub_ln77_fu_571_p2 <= std_logic_vector(unsigned(select_ln86_1_reg_888) - unsigned(x_s_reg_882));
    sub_ln81_fu_575_p2 <= std_logic_vector(unsigned(select_ln86_2_reg_864) - unsigned(y_s_reg_909));
    sub_ln83_fu_615_p2 <= std_logic_vector(unsigned(select_ln61_reg_985) - unsigned(zext_ln73_fu_607_p1));
    tmp_72_fu_526_p4 <= add_ln42_fu_475_p2(33 downto 2);
    tmp_85_cast_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_72_fu_526_p4),33));
    tmp_s_fu_516_p4 <= sub_ln228_fu_494_p2(33 downto 1);
    trunc_ln42_fu_404_p1 <= inabs_fu_397_p3(21 - 1 downto 0);
    trunc_ln61_2_fu_603_p1 <= x_fu_583_p3(33 - 1 downto 0);
    trunc_ln61_fu_599_p1 <= y_fu_591_p3(33 - 1 downto 0);
    trunc_ln7_fu_715_p4 <= outsin_0_in_in_i_fu_660_p9(32 downto 11);
    x_fu_583_p3 <= 
        add_ln76_fu_567_p2 when (d_1_fu_559_p3(0) = '1') else 
        sub_ln81_fu_575_p2;
    x_s_fu_371_p2 <= std_logic_vector(shift_right(signed(select_ln86_2_fu_351_p3),to_integer(unsigned('0' & zext_ln71_fu_368_p1(31-1 downto 0)))));
    y_fu_591_p3 <= 
        sub_ln77_fu_571_p2 when (d_1_fu_559_p3(0) = '1') else 
        add_ln82_fu_579_p2;
    y_s_fu_408_p2 <= std_logic_vector(shift_right(signed(select_ln86_1_fu_380_p3),to_integer(unsigned('0' & zext_ln71_reg_877(31-1 downto 0)))));
    z_fu_620_p3 <= 
        add_ln78_fu_610_p2 when (d_1_reg_991(0) = '1') else 
        sub_ln83_fu_615_p2;
    zext_ln42_2_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_480_p4),34));
    zext_ln61_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln86_reg_838_pp0_iter3_reg),64));
    zext_ln71_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln86_reg_838_pp0_iter3_reg),34));
    zext_ln73_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_73_reg_959),34));
    zext_ln86_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln86_3_reg_845_pp0_iter3_reg),64));
end behav;
