-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln61 : IN STD_LOGIC_VECTOR (64 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (64 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (64 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC );
end;


architecture behav of qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv66_0 : STD_LOGIC_VECTOR (65 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv66_4DBA76D421AF23F9 : STD_LOGIC_VECTOR (65 downto 0) := "000100110110111010011101101101010000100001101011110010001111111001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_42 : STD_LOGIC_VECTOR (6 downto 0) := "1000010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln61_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal circ_table_arctan_1289_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal circ_table_arctan_1289_q0 : STD_LOGIC_VECTOR (125 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_load6_reg_298 : STD_LOGIC_VECTOR (65 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal p_load_reg_304 : STD_LOGIC_VECTOR (65 downto 0);
    signal icmp_ln61_reg_310 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_s_fu_165_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal x_s_reg_314 : STD_LOGIC_VECTOR (65 downto 0);
    signal y_s_fu_171_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal y_s_reg_320 : STD_LOGIC_VECTOR (65 downto 0);
    signal p_load7_reg_331 : STD_LOGIC_VECTOR (65 downto 0);
    signal d_fu_185_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_reg_337 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_342 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln61_fu_156_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal empty_fu_52 : STD_LOGIC_VECTOR (65 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000";
    signal tz_fu_258_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal sext_ln61_cast_fu_101_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_55_fu_56 : STD_LOGIC_VECTOR (65 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000";
    signal tx_fu_219_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal empty_56_fu_60 : STD_LOGIC_VECTOR (65 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000";
    signal ty_fu_227_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal n_fu_64 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln61_fu_150_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal circ_table_arctan_1289_ce0_local : STD_LOGIC;
    signal zext_ln71_fu_161_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal add_ln76_fu_203_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal sub_ln81_fu_211_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal sub_ln77_fu_207_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal add_ln82_fu_215_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal zext_ln73_fu_245_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal add_ln78_fu_248_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal sub_ln83_fu_253_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component qaoa_kernel_applyCost_hls_3_s_cordic_apfixed_circ_table_arctan_128_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (125 downto 0) );
    end component;


    component qaoa_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    circ_table_arctan_1289_U : component qaoa_kernel_applyCost_hls_3_s_cordic_apfixed_circ_table_arctan_128_ROM_AUTO_1R
    generic map (
        DataWidth => 126,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => circ_table_arctan_1289_address0,
        ce0 => circ_table_arctan_1289_ce0_local,
        q0 => circ_table_arctan_1289_q0);

    flow_control_loop_pipe_sequential_init_U : component qaoa_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    empty_55_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_55_fu_56 <= ap_const_lv66_4DBA76D421AF23F9;
                elsif (((icmp_ln61_reg_310 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_55_fu_56 <= tx_fu_219_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_56_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_56_fu_60 <= ap_const_lv66_0;
                elsif (((icmp_ln61_reg_310 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_56_fu_60 <= ty_fu_227_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                empty_fu_52 <= sext_ln61_cast_fu_101_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                empty_fu_52 <= tz_fu_258_p3;
            end if; 
        end if;
    end process;

    n_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                n_fu_64 <= ap_const_lv7_0;
            elsif (((icmp_ln61_fu_144_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                n_fu_64 <= add_ln61_fu_150_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                d_reg_337 <= empty_fu_52(65 downto 65);
                p_load7_reg_331 <= empty_fu_52;
                tmp_s_reg_342 <= circ_table_arctan_1289_q0(125 downto 63);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln61_reg_310 <= icmp_ln61_fu_144_p2;
                p_load6_reg_298 <= empty_55_fu_56;
                p_load_reg_304 <= empty_56_fu_60;
                x_s_reg_314 <= x_s_fu_165_p2;
                y_s_reg_320 <= y_s_fu_171_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln61_fu_150_p2 <= std_logic_vector(unsigned(n_fu_64) + unsigned(ap_const_lv7_1));
    add_ln76_fu_203_p2 <= std_logic_vector(unsigned(p_load6_reg_298) + unsigned(y_s_reg_320));
    add_ln78_fu_248_p2 <= std_logic_vector(unsigned(zext_ln73_fu_245_p1) + unsigned(p_load7_reg_331));
    add_ln82_fu_215_p2 <= std_logic_vector(unsigned(x_s_reg_314) + unsigned(p_load_reg_304));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln61_fu_144_p2)
    begin
        if (((icmp_ln61_fu_144_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    circ_table_arctan_1289_address0 <= zext_ln61_fu_156_p1(7 - 1 downto 0);

    circ_table_arctan_1289_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            circ_table_arctan_1289_ce0_local <= ap_const_logic_1;
        else 
            circ_table_arctan_1289_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    d_fu_185_p3 <= empty_fu_52(65 downto 65);
    icmp_ln61_fu_144_p2 <= "1" when (n_fu_64 = ap_const_lv7_42) else "0";
    p_out <= empty_56_fu_60(65 - 1 downto 0);
    p_out1 <= empty_55_fu_56(65 - 1 downto 0);

    p_out1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln61_fu_144_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln61_fu_144_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln61_fu_144_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln61_fu_144_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln61_cast_fu_101_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln61),66));

    sub_ln77_fu_207_p2 <= std_logic_vector(unsigned(p_load_reg_304) - unsigned(x_s_reg_314));
    sub_ln81_fu_211_p2 <= std_logic_vector(unsigned(p_load6_reg_298) - unsigned(y_s_reg_320));
    sub_ln83_fu_253_p2 <= std_logic_vector(unsigned(p_load7_reg_331) - unsigned(zext_ln73_fu_245_p1));
    tx_fu_219_p3 <= 
        add_ln76_fu_203_p2 when (d_fu_185_p3(0) = '1') else 
        sub_ln81_fu_211_p2;
    ty_fu_227_p3 <= 
        sub_ln77_fu_207_p2 when (d_fu_185_p3(0) = '1') else 
        add_ln82_fu_215_p2;
    tz_fu_258_p3 <= 
        add_ln78_fu_248_p2 when (d_reg_337(0) = '1') else 
        sub_ln83_fu_253_p2;
    x_s_fu_165_p2 <= std_logic_vector(shift_right(signed(empty_55_fu_56),to_integer(unsigned('0' & zext_ln71_fu_161_p1(31-1 downto 0)))));
    y_s_fu_171_p2 <= std_logic_vector(shift_right(signed(empty_56_fu_60),to_integer(unsigned('0' & zext_ln71_fu_161_p1(31-1 downto 0)))));
    zext_ln61_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_fu_64),64));
    zext_ln71_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_fu_64),66));
    zext_ln73_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_342),66));
end behav;
