// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln128_1,
        shl49,
        mask,
        bufB_re_address0,
        bufB_re_ce0,
        bufB_re_q0,
        bufB_re_address1,
        bufB_re_ce1,
        bufB_re_we1,
        bufB_re_d1,
        bufB_re_q1,
        bufB_im_address0,
        bufB_im_ce0,
        bufB_im_q0,
        bufB_im_address1,
        bufB_im_ce1,
        bufB_im_we1,
        bufB_im_d1,
        bufB_im_q1,
        bufA_re_address0,
        bufA_re_ce0,
        bufA_re_q0,
        bufA_re_address1,
        bufA_re_ce1,
        bufA_re_we1,
        bufA_re_d1,
        bufA_re_q1,
        bufA_im_address0,
        bufA_im_ce0,
        bufA_im_q0,
        bufA_im_address1,
        bufA_im_ce1,
        bufA_im_we1,
        bufA_im_d1,
        bufA_im_q1,
        state_cur_223131,
        trunc_ln102_cast,
        sext_ln127,
        state_next_222129,
        grp_fu_917_p_din0,
        grp_fu_917_p_din1,
        grp_fu_917_p_dout0,
        grp_fu_917_p_ce
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] zext_ln128_1;
input  [2:0] shl49;
input  [8:0] mask;
output  [8:0] bufB_re_address0;
output   bufB_re_ce0;
input  [31:0] bufB_re_q0;
output  [8:0] bufB_re_address1;
output   bufB_re_ce1;
output   bufB_re_we1;
output  [31:0] bufB_re_d1;
input  [31:0] bufB_re_q1;
output  [8:0] bufB_im_address0;
output   bufB_im_ce0;
input  [31:0] bufB_im_q0;
output  [8:0] bufB_im_address1;
output   bufB_im_ce1;
output   bufB_im_we1;
output  [31:0] bufB_im_d1;
input  [31:0] bufB_im_q1;
output  [8:0] bufA_re_address0;
output   bufA_re_ce0;
input  [31:0] bufA_re_q0;
output  [8:0] bufA_re_address1;
output   bufA_re_ce1;
output   bufA_re_we1;
output  [31:0] bufA_re_d1;
input  [31:0] bufA_re_q1;
output  [8:0] bufA_im_address0;
output   bufA_im_ce0;
input  [31:0] bufA_im_q0;
output  [8:0] bufA_im_address1;
output   bufA_im_ce1;
output   bufA_im_we1;
output  [31:0] bufA_im_d1;
input  [31:0] bufA_im_q1;
input  [0:0] state_cur_223131;
input  [21:0] trunc_ln102_cast;
input  [21:0] sext_ln127;
input  [0:0] state_next_222129;
output  [31:0] grp_fu_917_p_din0;
output  [21:0] grp_fu_917_p_din1;
input  [51:0] grp_fu_917_p_dout0;
output   grp_fu_917_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln140_fu_272_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state4;
wire   [0:0] state_next_222129_read_reg_469;
wire   [0:0] state_cur_223131_read_read_fu_92_p2;
wire  signed [51:0] sext_ln127_cast_fu_252_p1;
reg  signed [51:0] sext_ln127_cast_reg_481;
wire  signed [51:0] trunc_ln102_cast_cast_fu_256_p1;
reg  signed [51:0] trunc_ln102_cast_cast_reg_489;
reg   [0:0] icmp_ln140_reg_497;
wire   [9:0] add_ln140_fu_278_p2;
reg   [9:0] add_ln140_reg_501;
wire   [0:0] icmp_ln144_fu_306_p2;
reg   [0:0] icmp_ln144_reg_506;
reg   [8:0] bufB_re_addr_reg_510;
reg   [8:0] bufB_im_addr_reg_515;
reg   [8:0] bufB_re_addr_1_reg_520;
reg   [8:0] bufB_im_addr_1_reg_526;
reg   [8:0] bufA_re_addr_reg_532;
reg   [8:0] bufA_im_addr_reg_537;
reg   [8:0] bufA_re_addr_1_reg_542;
reg   [8:0] bufA_im_addr_1_reg_548;
wire  signed [51:0] sext_ln56_fu_354_p1;
reg  signed [51:0] sext_ln56_reg_554;
wire    ap_CS_fsm_state2;
wire  signed [51:0] sext_ln56_1_fu_359_p1;
reg  signed [51:0] sext_ln56_1_reg_560;
wire  signed [51:0] sext_ln56_2_fu_364_p1;
reg  signed [51:0] sext_ln56_2_reg_566;
wire  signed [51:0] sext_ln56_3_fu_369_p1;
reg  signed [51:0] sext_ln56_3_reg_572;
wire   [63:0] zext_ln140_fu_284_p1;
wire   [63:0] zext_ln147_fu_318_p1;
reg   [9:0] s_idx_fu_70;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_s_idx_1;
reg    bufB_re_ce1_local;
reg   [8:0] bufB_re_address1_local;
reg    bufB_re_ce0_local;
reg    bufB_re_we1_local;
wire    ap_CS_fsm_state3;
reg   [31:0] bufB_re_d1_local;
wire   [31:0] sub_ln62_fu_400_p2;
wire   [31:0] add_ln59_fu_442_p2;
reg    bufB_im_ce1_local;
reg   [8:0] bufB_im_address1_local;
reg    bufB_im_ce0_local;
reg    bufB_im_we1_local;
reg   [31:0] bufB_im_d1_local;
wire   [31:0] sub_ln62_1_fu_408_p2;
wire   [31:0] add_ln59_1_fu_450_p2;
reg    bufA_re_ce1_local;
reg   [8:0] bufA_re_address1_local;
reg    bufA_re_ce0_local;
reg    bufA_re_we1_local;
reg   [31:0] bufA_re_d1_local;
reg    bufA_im_ce1_local;
reg   [8:0] bufA_im_address1_local;
reg    bufA_im_ce0_local;
reg    bufA_im_we1_local;
reg   [31:0] bufA_im_d1_local;
reg  signed [31:0] grp_fu_216_p0;
reg  signed [21:0] grp_fu_216_p1;
reg  signed [31:0] grp_fu_220_p0;
reg  signed [21:0] grp_fu_220_p1;
reg  signed [31:0] grp_fu_224_p0;
reg  signed [21:0] grp_fu_224_p1;
reg  signed [31:0] grp_fu_228_p0;
reg  signed [21:0] grp_fu_228_p1;
wire   [51:0] grp_fu_228_p2;
wire   [8:0] trunc_ln141_fu_292_p1;
wire   [8:0] zext_ln128_1_cast_fu_260_p1;
wire   [8:0] lshr_ln141_fu_296_p2;
wire   [2:0] slice_fu_302_p1;
wire   [8:0] s_flip_fu_312_p2;
wire   [31:0] empty_58_fu_333_p3;
wire   [31:0] empty_59_fu_340_p3;
wire   [31:0] empty_fu_326_p3;
wire   [31:0] b_im_fu_347_p3;
wire   [51:0] grp_fu_220_p2;
wire   [51:0] grp_fu_224_p2;
wire   [51:0] sub_ln56_fu_384_p2;
wire   [31:0] grp_fu_232_p4;
wire   [31:0] trunc_ln56_2_fu_390_p4;
wire   [31:0] trunc_ln56_1_fu_374_p4;
wire   [31:0] grp_fu_242_p4;
wire   [51:0] sub_ln56_1_fu_416_p2;
wire   [31:0] trunc_ln56_6_fu_432_p4;
wire   [31:0] trunc_ln56_5_fu_422_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_228;
reg    ap_condition_181;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 s_idx_fu_70 = 10'd0;
#0 ap_done_reg = 1'b0;
end

qaoa_kernel_mul_32s_22s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 52 ))
mul_32s_22s_52_2_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_220_p0),
    .din1(grp_fu_220_p1),
    .ce(1'b1),
    .dout(grp_fu_220_p2)
);

qaoa_kernel_mul_32s_22s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 52 ))
mul_32s_22s_52_2_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .ce(1'b1),
    .dout(grp_fu_224_p2)
);

qaoa_kernel_mul_32s_22s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 52 ))
mul_32s_22s_52_2_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_228_p0),
    .din1(grp_fu_228_p1),
    .ce(1'b1),
    .dout(grp_fu_228_p2)
);

qaoa_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        s_idx_fu_70 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln140_reg_497 == 1'd0))) begin
        s_idx_fu_70 <= add_ln140_reg_501;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln140_reg_501 <= add_ln140_fu_278_p2;
        bufA_im_addr_1_reg_548 <= zext_ln147_fu_318_p1;
        bufA_im_addr_reg_537 <= zext_ln140_fu_284_p1;
        bufA_re_addr_1_reg_542 <= zext_ln147_fu_318_p1;
        bufA_re_addr_reg_532 <= zext_ln140_fu_284_p1;
        bufB_im_addr_1_reg_526 <= zext_ln147_fu_318_p1;
        bufB_im_addr_reg_515 <= zext_ln140_fu_284_p1;
        bufB_re_addr_1_reg_520 <= zext_ln147_fu_318_p1;
        bufB_re_addr_reg_510 <= zext_ln140_fu_284_p1;
        icmp_ln140_reg_497 <= icmp_ln140_fu_272_p2;
        icmp_ln144_reg_506 <= icmp_ln144_fu_306_p2;
        sext_ln127_cast_reg_481 <= sext_ln127_cast_fu_252_p1;
        trunc_ln102_cast_cast_reg_489 <= trunc_ln102_cast_cast_fu_256_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sext_ln56_1_reg_560 <= sext_ln56_1_fu_359_p1;
        sext_ln56_2_reg_566 <= sext_ln56_2_fu_364_p1;
        sext_ln56_3_reg_572 <= sext_ln56_3_fu_369_p1;
        sext_ln56_reg_554 <= sext_ln56_fu_354_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln140_fu_272_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_s_idx_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_s_idx_1 = s_idx_fu_70;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufA_im_address1_local = bufA_im_addr_1_reg_548;
    end else if (((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufA_im_address1_local = bufA_im_addr_reg_537;
    end else if (((state_cur_223131_read_read_fu_92_p2 == 1'd0) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1))) begin
        bufA_im_address1_local = zext_ln140_fu_284_p1;
    end else begin
        bufA_im_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        bufA_im_ce0_local = 1'b1;
    end else begin
        bufA_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_cur_223131_read_read_fu_92_p2 == 1'd0) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1)))) begin
        bufA_im_ce1_local = 1'b1;
    end else begin
        bufA_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_228)) begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            bufA_im_d1_local = add_ln59_1_fu_450_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            bufA_im_d1_local = sub_ln62_1_fu_408_p2;
        end else begin
            bufA_im_d1_local = 'bx;
        end
    end else begin
        bufA_im_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)))) begin
        bufA_im_we1_local = 1'b1;
    end else begin
        bufA_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufA_re_address1_local = bufA_re_addr_1_reg_542;
    end else if (((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufA_re_address1_local = bufA_re_addr_reg_532;
    end else if (((state_cur_223131_read_read_fu_92_p2 == 1'd0) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1))) begin
        bufA_re_address1_local = zext_ln140_fu_284_p1;
    end else begin
        bufA_re_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        bufA_re_ce0_local = 1'b1;
    end else begin
        bufA_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_cur_223131_read_read_fu_92_p2 == 1'd0) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1)))) begin
        bufA_re_ce1_local = 1'b1;
    end else begin
        bufA_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_228)) begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            bufA_re_d1_local = add_ln59_fu_442_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            bufA_re_d1_local = sub_ln62_fu_400_p2;
        end else begin
            bufA_re_d1_local = 'bx;
        end
    end else begin
        bufA_re_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)))) begin
        bufA_re_we1_local = 1'b1;
    end else begin
        bufA_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufB_im_address1_local = bufB_im_addr_1_reg_526;
    end else if (((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufB_im_address1_local = bufB_im_addr_reg_515;
    end else if (((state_cur_223131_read_read_fu_92_p2 == 1'd1) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1))) begin
        bufB_im_address1_local = zext_ln140_fu_284_p1;
    end else begin
        bufB_im_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        bufB_im_ce0_local = 1'b1;
    end else begin
        bufB_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_cur_223131_read_read_fu_92_p2 == 1'd1) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1)))) begin
        bufB_im_ce1_local = 1'b1;
    end else begin
        bufB_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_181)) begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            bufB_im_d1_local = add_ln59_1_fu_450_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            bufB_im_d1_local = sub_ln62_1_fu_408_p2;
        end else begin
            bufB_im_d1_local = 'bx;
        end
    end else begin
        bufB_im_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)))) begin
        bufB_im_we1_local = 1'b1;
    end else begin
        bufB_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufB_re_address1_local = bufB_re_addr_1_reg_520;
    end else if (((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0))) begin
        bufB_re_address1_local = bufB_re_addr_reg_510;
    end else if (((state_cur_223131_read_read_fu_92_p2 == 1'd1) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1))) begin
        bufB_re_address1_local = zext_ln140_fu_284_p1;
    end else begin
        bufB_re_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        bufB_re_ce0_local = 1'b1;
    end else begin
        bufB_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_cur_223131_read_read_fu_92_p2 == 1'd1) & (icmp_ln140_fu_272_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln144_fu_306_p2 == 1'd1)))) begin
        bufB_re_ce1_local = 1'b1;
    end else begin
        bufB_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_181)) begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            bufB_re_d1_local = add_ln59_fu_442_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            bufB_re_d1_local = sub_ln62_fu_400_p2;
        end else begin
            bufB_re_d1_local = 'bx;
        end
    end else begin
        bufB_re_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)) | ((state_next_222129_read_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0)))) begin
        bufB_re_we1_local = 1'b1;
    end else begin
        bufB_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_216_p0 = sext_ln56_1_reg_560;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_216_p0 = sext_ln56_fu_354_p1;
    end else begin
        grp_fu_216_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_216_p1 = sext_ln127_cast_reg_481;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_216_p1 = trunc_ln102_cast_cast_reg_489;
    end else begin
        grp_fu_216_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_220_p0 = sext_ln56_reg_554;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_220_p0 = sext_ln56_1_fu_359_p1;
    end else begin
        grp_fu_220_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_220_p1 = sext_ln127_cast_reg_481;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_220_p1 = trunc_ln102_cast_cast_reg_489;
    end else begin
        grp_fu_220_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_224_p0 = sext_ln56_2_reg_566;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_224_p0 = sext_ln56_3_fu_369_p1;
    end else begin
        grp_fu_224_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_224_p1 = trunc_ln102_cast_cast_reg_489;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_224_p1 = sext_ln127_cast_reg_481;
    end else begin
        grp_fu_224_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_228_p0 = sext_ln56_3_reg_572;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_228_p0 = sext_ln56_2_fu_364_p1;
    end else begin
        grp_fu_228_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_228_p1 = trunc_ln102_cast_cast_reg_489;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_228_p1 = sext_ln127_cast_reg_481;
    end else begin
        grp_fu_228_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln140_fu_272_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln140_fu_278_p2 = (ap_sig_allocacmp_s_idx_1 + 10'd1);

assign add_ln59_1_fu_450_p2 = (grp_fu_242_p4 + trunc_ln56_5_fu_422_p4);

assign add_ln59_fu_442_p2 = (grp_fu_232_p4 + trunc_ln56_6_fu_432_p4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_condition_181 = ((state_next_222129_read_reg_469 == 1'd1) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0));
end

always @ (*) begin
    ap_condition_228 = ((state_next_222129_read_reg_469 == 1'd0) & (icmp_ln144_reg_506 == 1'd1) & (icmp_ln140_reg_497 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_im_fu_347_p3 = ((state_cur_223131[0:0] == 1'b1) ? bufB_im_q0 : bufA_im_q0);

assign bufA_im_address0 = zext_ln147_fu_318_p1;

assign bufA_im_address1 = bufA_im_address1_local;

assign bufA_im_ce0 = bufA_im_ce0_local;

assign bufA_im_ce1 = bufA_im_ce1_local;

assign bufA_im_d1 = bufA_im_d1_local;

assign bufA_im_we1 = bufA_im_we1_local;

assign bufA_re_address0 = zext_ln147_fu_318_p1;

assign bufA_re_address1 = bufA_re_address1_local;

assign bufA_re_ce0 = bufA_re_ce0_local;

assign bufA_re_ce1 = bufA_re_ce1_local;

assign bufA_re_d1 = bufA_re_d1_local;

assign bufA_re_we1 = bufA_re_we1_local;

assign bufB_im_address0 = zext_ln147_fu_318_p1;

assign bufB_im_address1 = bufB_im_address1_local;

assign bufB_im_ce0 = bufB_im_ce0_local;

assign bufB_im_ce1 = bufB_im_ce1_local;

assign bufB_im_d1 = bufB_im_d1_local;

assign bufB_im_we1 = bufB_im_we1_local;

assign bufB_re_address0 = zext_ln147_fu_318_p1;

assign bufB_re_address1 = bufB_re_address1_local;

assign bufB_re_ce0 = bufB_re_ce0_local;

assign bufB_re_ce1 = bufB_re_ce1_local;

assign bufB_re_d1 = bufB_re_d1_local;

assign bufB_re_we1 = bufB_re_we1_local;

assign empty_58_fu_333_p3 = ((state_cur_223131[0:0] == 1'b1) ? bufB_re_q1 : bufA_re_q1);

assign empty_59_fu_340_p3 = ((state_cur_223131[0:0] == 1'b1) ? bufB_im_q1 : bufA_im_q1);

assign empty_fu_326_p3 = ((state_cur_223131[0:0] == 1'b1) ? bufB_re_q0 : bufA_re_q0);

assign grp_fu_232_p4 = {{grp_fu_917_p_dout0[51:20]}};

assign grp_fu_242_p4 = {{grp_fu_228_p2[51:20]}};

assign grp_fu_917_p_ce = 1'b1;

assign grp_fu_917_p_din0 = grp_fu_216_p0;

assign grp_fu_917_p_din1 = grp_fu_216_p1;

assign icmp_ln140_fu_272_p2 = ((ap_sig_allocacmp_s_idx_1 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_306_p2 = ((slice_fu_302_p1 == shl49) ? 1'b1 : 1'b0);

assign lshr_ln141_fu_296_p2 = trunc_ln141_fu_292_p1 >> zext_ln128_1_cast_fu_260_p1;

assign s_flip_fu_312_p2 = (trunc_ln141_fu_292_p1 ^ mask);

assign sext_ln127_cast_fu_252_p1 = $signed(sext_ln127);

assign sext_ln56_1_fu_359_p1 = $signed(empty_59_fu_340_p3);

assign sext_ln56_2_fu_364_p1 = $signed(empty_fu_326_p3);

assign sext_ln56_3_fu_369_p1 = $signed(b_im_fu_347_p3);

assign sext_ln56_fu_354_p1 = $signed(empty_58_fu_333_p3);

assign slice_fu_302_p1 = lshr_ln141_fu_296_p2[2:0];

assign state_cur_223131_read_read_fu_92_p2 = state_cur_223131;

assign state_next_222129_read_reg_469 = state_next_222129;

assign sub_ln56_1_fu_416_p2 = (52'd0 - grp_fu_220_p2);

assign sub_ln56_fu_384_p2 = (52'd0 - grp_fu_224_p2);

assign sub_ln62_1_fu_408_p2 = (trunc_ln56_1_fu_374_p4 - grp_fu_242_p4);

assign sub_ln62_fu_400_p2 = (grp_fu_232_p4 - trunc_ln56_2_fu_390_p4);

assign trunc_ln102_cast_cast_fu_256_p1 = $signed(trunc_ln102_cast);

assign trunc_ln141_fu_292_p1 = ap_sig_allocacmp_s_idx_1[8:0];

assign trunc_ln56_1_fu_374_p4 = {{grp_fu_220_p2[51:20]}};

assign trunc_ln56_2_fu_390_p4 = {{sub_ln56_fu_384_p2[51:20]}};

assign trunc_ln56_5_fu_422_p4 = {{sub_ln56_1_fu_416_p2[51:20]}};

assign trunc_ln56_6_fu_432_p4 = {{grp_fu_224_p2[51:20]}};

assign zext_ln128_1_cast_fu_260_p1 = zext_ln128_1;

assign zext_ln140_fu_284_p1 = ap_sig_allocacmp_s_idx_1;

assign zext_ln147_fu_318_p1 = s_flip_fu_312_p2;

endmodule //qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6
