// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_applyMixer_hls_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_re_address0,
        state_re_ce0,
        state_re_q0,
        state_re_address1,
        state_re_ce1,
        state_re_we1,
        state_re_d1,
        state_im_address0,
        state_im_ce0,
        state_im_q0,
        state_im_address1,
        state_im_ce1,
        state_im_we1,
        state_im_d1,
        beta,
        grp_fu_102_p_din0,
        grp_fu_102_p_din1,
        grp_fu_102_p_dout0,
        grp_fu_102_p_ce
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] state_re_address0;
output   state_re_ce0;
input  [31:0] state_re_q0;
output  [8:0] state_re_address1;
output   state_re_ce1;
output   state_re_we1;
output  [31:0] state_re_d1;
output  [8:0] state_im_address0;
output   state_im_ce0;
input  [31:0] state_im_q0;
output  [8:0] state_im_address1;
output   state_im_ce1;
output   state_im_we1;
output  [31:0] state_im_d1;
input  [31:0] beta;
output  [31:0] grp_fu_102_p_din0;
output  [21:0] grp_fu_102_p_din1;
input  [51:0] grp_fu_102_p_dout0;
output   grp_fu_102_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg state_re_ce0;
reg state_re_ce1;
reg state_re_we1;
reg state_im_ce0;
reg state_im_ce1;
reg state_im_we1;

(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] sign0_fu_354_p2;
reg   [0:0] sign0_reg_769;
wire   [52:0] inabs_fu_366_p3;
reg   [52:0] inabs_reg_774;
wire   [40:0] trunc_ln42_fu_374_p1;
reg   [40:0] trunc_ln42_reg_779;
wire    ap_CS_fsm_state2;
reg   [11:0] tmp_reg_789;
wire    ap_CS_fsm_state6;
reg   [1:0] k_3_reg_794;
wire    ap_CS_fsm_state7;
wire   [65:0] grp_fu_336_p2;
reg   [65:0] mul_ln42_reg_807;
wire    ap_CS_fsm_state11;
wire   [65:0] add_ln42_fu_418_p2;
reg   [65:0] add_ln42_reg_812;
wire    ap_CS_fsm_state12;
reg   [64:0] r_reg_817;
wire   [0:0] icmp_ln225_1_fu_447_p2;
reg   [0:0] icmp_ln225_1_reg_822;
wire    ap_CS_fsm_state13;
wire   [64:0] empty_fu_481_p3;
reg   [64:0] empty_reg_828;
wire   [0:0] icmp_ln248_fu_499_p2;
reg   [0:0] icmp_ln248_reg_833;
wire    ap_CS_fsm_state15;
reg   [41:0] trunc_ln1_reg_838;
reg   [21:0] tmp_100_reg_843;
reg   [21:0] lshr_ln_reg_848;
wire    ap_CS_fsm_state16;
wire   [21:0] select_ln265_fu_622_p3;
reg   [21:0] select_ln265_reg_853;
wire   [1:0] t_2_fu_637_p2;
reg   [1:0] t_2_reg_861;
wire    ap_CS_fsm_state17;
wire   [3:0] base_fu_655_p2;
reg   [3:0] base_reg_866;
wire   [31:0] zext_ln128_fu_661_p1;
reg   [31:0] zext_ln128_reg_871;
wire   [2:0] trunc_ln128_fu_665_p1;
reg   [2:0] trunc_ln128_reg_876;
wire   [1:0] j_3_fu_675_p2;
reg   [1:0] j_3_reg_884;
wire    ap_CS_fsm_state18;
wire   [31:0] zext_ln132_2_fu_689_p1;
wire   [8:0] bit_i_fu_702_p2;
reg   [8:0] bit_i_reg_894;
wire   [2:0] shl49_fu_708_p2;
reg   [2:0] shl49_reg_899;
wire   [8:0] mask_fu_739_p2;
reg   [8:0] mask_reg_907;
wire    ap_CS_fsm_state19;
wire   [31:0] j_fu_744_p2;
reg   [31:0] j_reg_912;
reg   [8:0] bufA_re_address0;
reg    bufA_re_ce0;
wire   [31:0] bufA_re_q0;
reg   [8:0] bufA_re_address1;
reg    bufA_re_ce1;
reg    bufA_re_we1;
reg   [31:0] bufA_re_d1;
wire   [31:0] bufA_re_q1;
reg   [8:0] bufA_im_address0;
reg    bufA_im_ce0;
wire   [31:0] bufA_im_q0;
reg   [8:0] bufA_im_address1;
reg    bufA_im_ce1;
reg    bufA_im_we1;
reg   [31:0] bufA_im_d1;
wire   [31:0] bufA_im_q1;
reg   [8:0] bufB_re_address0;
reg    bufB_re_ce0;
wire   [31:0] bufB_re_q0;
reg   [8:0] bufB_re_address1;
reg    bufB_re_ce1;
reg    bufB_re_we1;
reg   [31:0] bufB_re_d1;
wire   [31:0] bufB_re_q1;
reg   [8:0] bufB_im_address0;
reg    bufB_im_ce0;
wire   [31:0] bufB_im_q0;
reg   [8:0] bufB_im_address1;
reg    bufB_im_ce1;
reg    bufB_im_we1;
reg   [31:0] bufB_im_d1;
wire   [31:0] bufB_im_q1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_ready;
wire   [64:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out_ap_vld;
wire   [64:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out1_ap_vld;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_d1;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_d1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_d1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_im_ce0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_d1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_idle;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_d1;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_address0;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_address1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_ce1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_we1;
wire   [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_d1;
wire  signed [31:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_din0;
wire  signed [21:0] grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_din1;
wire    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_ce;
reg   [0:0] state_cur_030126_reg_168;
wire   [0:0] icmp_ln132_fu_669_p2;
reg   [0:0] state_next_029132_reg_180;
reg   [0:0] state_cur_127128_reg_192;
wire   [0:0] icmp_ln127_fu_631_p2;
wire   [0:0] icmp_ln132_1_fu_718_p2;
reg   [0:0] state_next_126130_reg_204;
reg   [1:0] i_reg_216;
reg   [0:0] state_cur_223131_reg_227;
reg   [0:0] state_next_222129_reg_239;
wire    ap_CS_fsm_state22;
reg   [31:0] j_1_reg_253;
reg    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start_reg;
wire    ap_CS_fsm_state14;
reg   [64:0] p_loc_fu_142;
reg   [64:0] p_loc160_fu_138;
reg    grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start_reg;
reg    grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start_reg;
reg    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start_reg;
reg    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start_reg;
wire    ap_CS_fsm_state23;
reg    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start_reg;
wire    ap_CS_fsm_state20;
reg    grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start_reg;
wire    ap_CS_fsm_state21;
reg   [1:0] t_fu_134;
wire   [11:0] grp_fu_336_p0;
wire   [64:0] grp_fu_336_p1;
wire   [52:0] grp_fu_341_p0;
wire   [89:0] grp_fu_341_p1;
wire   [52:0] x_1_fu_346_p3;
wire   [52:0] sub_ln211_fu_360_p2;
wire   [140:0] grp_fu_341_p2;
wire   [65:0] shl_ln_fu_411_p3;
wire   [65:0] zext_ln42_1_fu_433_p1;
wire   [0:0] icmp_ln225_fu_442_p2;
wire   [65:0] sub_ln228_fu_436_p2;
wire   [63:0] tmp_71_fu_468_p4;
wire   [0:0] or_ln225_fu_452_p2;
wire   [64:0] tmp_s_fu_458_p4;
wire   [64:0] tmp_81_cast_fu_477_p1;
wire   [0:0] icmp_ln248_1_fu_504_p2;
wire   [0:0] or_ln248_fu_509_p2;
wire   [64:0] sub_ln261_fu_493_p2;
wire   [64:0] outsin_0_in_in_i_fu_522_p7;
wire   [1:0] outsin_0_in_in_i_fu_522_p8;
wire   [64:0] outsin_0_in_in_i_fu_522_p9;
wire   [64:0] sub_ln254_fu_565_p2;
wire   [64:0] outcos_write_assign_in_in_i_fu_577_p7;
wire   [1:0] outcos_write_assign_in_in_i_fu_577_p8;
wire   [64:0] outcos_write_assign_in_in_i_fu_577_p9;
wire   [41:0] sub_ln266_fu_607_p2;
wire   [21:0] tmp_101_fu_612_p4;
wire   [3:0] p_shl_fu_647_p3;
wire   [3:0] zext_ln127_fu_643_p1;
wire   [3:0] zext_ln132_1_fu_685_p1;
wire   [3:0] add41_fu_693_p2;
wire   [8:0] add41_cast_fu_698_p1;
wire   [2:0] zext_ln132_fu_681_p1;
wire   [31:0] add_ln137_fu_724_p2;
wire   [31:0] bit_j_fu_729_p2;
wire   [8:0] trunc_ln137_fu_735_p1;
reg    grp_fu_917_ce;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_block_state14_on_subcall_done;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire   [65:0] grp_fu_336_p00;
wire   [140:0] grp_fu_341_p00;
wire  signed [1:0] outsin_0_in_in_i_fu_522_p1;
wire   [1:0] outsin_0_in_in_i_fu_522_p3;
wire   [1:0] outsin_0_in_in_i_fu_522_p5;
wire  signed [1:0] outcos_write_assign_in_in_i_fu_577_p1;
wire   [1:0] outcos_write_assign_in_in_i_fu_577_p3;
wire   [1:0] outcos_write_assign_in_in_i_fu_577_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
#0 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start_reg = 1'b0;
#0 t_fu_134 = 2'd0;
end

qaoa_kernel_applyMixer_hls_3_s_bufA_re_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
bufA_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bufA_re_address0),
    .ce0(bufA_re_ce0),
    .q0(bufA_re_q0),
    .address1(bufA_re_address1),
    .ce1(bufA_re_ce1),
    .we1(bufA_re_we1),
    .d1(bufA_re_d1),
    .q1(bufA_re_q1)
);

qaoa_kernel_applyMixer_hls_3_s_bufA_re_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
bufA_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bufA_im_address0),
    .ce0(bufA_im_ce0),
    .q0(bufA_im_q0),
    .address1(bufA_im_address1),
    .ce1(bufA_im_ce1),
    .we1(bufA_im_we1),
    .d1(bufA_im_d1),
    .q1(bufA_im_q1)
);

qaoa_kernel_applyMixer_hls_3_s_bufA_re_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
bufB_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bufB_re_address0),
    .ce0(bufB_re_ce0),
    .q0(bufB_re_q0),
    .address1(bufB_re_address1),
    .ce1(bufB_re_ce1),
    .we1(bufB_re_we1),
    .d1(bufB_re_d1),
    .q1(bufB_re_q1)
);

qaoa_kernel_applyMixer_hls_3_s_bufA_re_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
bufB_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bufB_im_address0),
    .ce0(bufB_im_ce0),
    .q0(bufB_im_q0),
    .address1(bufB_im_address1),
    .ce1(bufB_im_ce1),
    .we1(bufB_im_we1),
    .d1(bufB_im_d1),
    .q1(bufB_im_q1)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_ready),
    .sext_ln61(empty_reg_828),
    .p_out(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out),
    .p_out_ap_vld(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out_ap_vld),
    .p_out1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out1),
    .p_out1_ap_vld(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out1_ap_vld)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_2 grp_applyMixer_hls_3_Pipeline_2_fu_271(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_ready),
    .bufA_re_address1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_address1),
    .bufA_re_ce1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_ce1),
    .bufA_re_we1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_we1),
    .bufA_re_d1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_d1),
    .bufA_im_address1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_address1),
    .bufA_im_ce1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_ce1),
    .bufA_im_we1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_we1),
    .bufA_im_d1(grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_d1)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_3 grp_applyMixer_hls_3_Pipeline_3_fu_277(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_ready),
    .bufB_re_address1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_address1),
    .bufB_re_ce1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_ce1),
    .bufB_re_we1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_we1),
    .bufB_re_d1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_d1),
    .bufB_im_address1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_address1),
    .bufB_im_ce1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_ce1),
    .bufB_im_we1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_we1),
    .bufB_im_d1(grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_d1)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_ready),
    .state_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_re_address0),
    .state_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_re_ce0),
    .state_re_q0(state_re_q0),
    .state_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_im_address0),
    .state_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_im_ce0),
    .state_im_q0(state_im_q0),
    .bufA_re_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_address1),
    .bufA_re_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_ce1),
    .bufA_re_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_we1),
    .bufA_re_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_d1),
    .bufA_im_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_address1),
    .bufA_im_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_ce1),
    .bufA_im_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_we1),
    .bufA_im_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_d1)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_ready),
    .state_re_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_address1),
    .state_re_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_ce1),
    .state_re_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_we1),
    .state_re_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_d1),
    .state_im_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_address1),
    .state_im_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_ce1),
    .state_im_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_we1),
    .state_im_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_d1),
    .bufB_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_re_address0),
    .bufB_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_re_ce0),
    .bufB_re_q0(bufB_re_q0),
    .bufB_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_im_address0),
    .bufB_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_im_ce0),
    .bufB_im_q0(bufB_im_q0),
    .bufA_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_re_address0),
    .bufA_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_re_ce0),
    .bufA_re_q0(bufA_re_q0),
    .bufA_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_im_address0),
    .bufA_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_im_ce0),
    .bufA_im_q0(bufA_im_q0),
    .state_cur_030126(state_cur_030126_reg_168)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_ready),
    .bufB_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_address0),
    .bufB_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_ce0),
    .bufB_re_q0(bufB_re_q0),
    .bufB_re_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_address1),
    .bufB_re_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_ce1),
    .bufB_re_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_we1),
    .bufB_re_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_d1),
    .bufB_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_address0),
    .bufB_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_ce0),
    .bufB_im_q0(bufB_im_q0),
    .bufB_im_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_address1),
    .bufB_im_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_ce1),
    .bufB_im_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_we1),
    .bufB_im_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_d1),
    .bufA_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_address0),
    .bufA_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_ce0),
    .bufA_re_q0(bufA_re_q0),
    .bufA_re_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_address1),
    .bufA_re_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_ce1),
    .bufA_re_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_we1),
    .bufA_re_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_d1),
    .bufA_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_address0),
    .bufA_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_ce0),
    .bufA_im_q0(bufA_im_q0),
    .bufA_im_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_address1),
    .bufA_im_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_ce1),
    .bufA_im_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_we1),
    .bufA_im_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_d1),
    .state_cur_223131(state_cur_223131_reg_227),
    .state_next_222129(state_next_222129_reg_239)
);

qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6 grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start),
    .ap_done(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done),
    .ap_idle(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_ready),
    .zext_ln128_1(trunc_ln128_reg_876),
    .shl49(shl49_reg_899),
    .mask(mask_reg_907),
    .bufB_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_address0),
    .bufB_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_ce0),
    .bufB_re_q0(bufB_re_q0),
    .bufB_re_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_address1),
    .bufB_re_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_ce1),
    .bufB_re_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_we1),
    .bufB_re_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_d1),
    .bufB_re_q1(bufB_re_q1),
    .bufB_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_address0),
    .bufB_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_ce0),
    .bufB_im_q0(bufB_im_q0),
    .bufB_im_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_address1),
    .bufB_im_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_ce1),
    .bufB_im_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_we1),
    .bufB_im_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_d1),
    .bufB_im_q1(bufB_im_q1),
    .bufA_re_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_address0),
    .bufA_re_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_ce0),
    .bufA_re_q0(bufA_re_q0),
    .bufA_re_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_address1),
    .bufA_re_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_ce1),
    .bufA_re_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_we1),
    .bufA_re_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_d1),
    .bufA_re_q1(bufA_re_q1),
    .bufA_im_address0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_address0),
    .bufA_im_ce0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_ce0),
    .bufA_im_q0(bufA_im_q0),
    .bufA_im_address1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_address1),
    .bufA_im_ce1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_ce1),
    .bufA_im_we1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_we1),
    .bufA_im_d1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_d1),
    .bufA_im_q1(bufA_im_q1),
    .state_cur_223131(state_cur_223131_reg_227),
    .trunc_ln102_cast(lshr_ln_reg_848),
    .sext_ln127(select_ln265_reg_853),
    .state_next_222129(state_next_222129_reg_239),
    .grp_fu_917_p_din0(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_din0),
    .grp_fu_917_p_din1(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_din1),
    .grp_fu_917_p_dout0(grp_fu_102_p_dout0),
    .grp_fu_917_p_ce(grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_ce)
);

qaoa_kernel_mul_12ns_65ns_66_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 65 ),
    .dout_WIDTH( 66 ))
mul_12ns_65ns_66_5_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_336_p0),
    .din1(grp_fu_336_p1),
    .ce(1'b1),
    .dout(grp_fu_336_p2)
);

qaoa_kernel_mul_53ns_90ns_141_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 53 ),
    .din1_WIDTH( 90 ),
    .dout_WIDTH( 141 ))
mul_53ns_90ns_141_5_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_341_p0),
    .din1(grp_fu_341_p1),
    .ce(1'b1),
    .dout(grp_fu_341_p2)
);

(* dissolve_hierarchy = "yes" *) qaoa_kernel_sparsemux_7_2_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 65 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 65 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 65 ),
    .def_WIDTH( 65 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 65 ))
sparsemux_7_2_65_1_1_U64(
    .din0(sub_ln261_fu_493_p2),
    .din1(p_loc_fu_142),
    .din2(sub_ln261_fu_493_p2),
    .def(outsin_0_in_in_i_fu_522_p7),
    .sel(outsin_0_in_in_i_fu_522_p8),
    .dout(outsin_0_in_in_i_fu_522_p9)
);

(* dissolve_hierarchy = "yes" *) qaoa_kernel_sparsemux_7_2_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 65 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 65 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 65 ),
    .def_WIDTH( 65 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 65 ))
sparsemux_7_2_65_1_1_U65(
    .din0(sub_ln254_fu_565_p2),
    .din1(sub_ln254_fu_565_p2),
    .din2(p_loc160_fu_138),
    .def(outcos_write_assign_in_in_i_fu_577_p7),
    .sel(outcos_write_assign_in_in_i_fu_577_p8),
    .dout(outcos_write_assign_in_in_i_fu_577_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln132_1_fu_718_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln127_fu_631_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_1_fu_718_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        i_reg_216 <= j_3_reg_884;
    end else if (((icmp_ln127_fu_631_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        i_reg_216 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        j_1_reg_253 <= j_reg_912;
    end else if (((icmp_ln132_fu_669_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        j_1_reg_253 <= zext_ln132_2_fu_689_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_fu_669_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        state_cur_030126_reg_168 <= state_cur_127128_reg_192;
    end else if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        state_cur_030126_reg_168 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_1_fu_718_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        state_cur_127128_reg_192 <= state_cur_223131_reg_227;
    end else if (((icmp_ln127_fu_631_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        state_cur_127128_reg_192 <= state_cur_030126_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        state_cur_223131_reg_227 <= state_next_222129_reg_239;
    end else if (((icmp_ln132_fu_669_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        state_cur_223131_reg_227 <= state_cur_127128_reg_192;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_fu_669_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        state_next_029132_reg_180 <= state_next_126130_reg_204;
    end else if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        state_next_029132_reg_180 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_1_fu_718_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        state_next_126130_reg_204 <= state_next_222129_reg_239;
    end else if (((icmp_ln127_fu_631_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        state_next_126130_reg_204 <= state_next_029132_reg_180;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        state_next_222129_reg_239 <= state_cur_223131_reg_227;
    end else if (((icmp_ln132_fu_669_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        state_next_222129_reg_239 <= state_next_126130_reg_204;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_fu_134 <= 2'd0;
    end else if (((icmp_ln132_fu_669_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        t_fu_134 <= t_2_reg_861;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln42_reg_812 <= add_ln42_fu_418_p2;
        r_reg_817 <= {{add_ln42_fu_418_p2[65:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        base_reg_866 <= base_fu_655_p2;
        t_2_reg_861 <= t_2_fu_637_p2;
        trunc_ln128_reg_876 <= trunc_ln128_fu_665_p1;
        zext_ln128_reg_871[3 : 0] <= zext_ln128_fu_661_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        bit_i_reg_894 <= bit_i_fu_702_p2;
        j_3_reg_884 <= j_3_fu_675_p2;
        shl49_reg_899 <= shl49_fu_708_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        empty_reg_828 <= empty_fu_481_p3;
        icmp_ln225_1_reg_822 <= icmp_ln225_1_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln248_reg_833 <= icmp_ln248_fu_499_p2;
        tmp_100_reg_843 <= {{outsin_0_in_in_i_fu_522_p9[64:43]}};
        trunc_ln1_reg_838 <= {{outsin_0_in_in_i_fu_522_p9[64:23]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        inabs_reg_774[52 : 21] <= inabs_fu_366_p3[52 : 21];
        sign0_reg_769 <= sign0_fu_354_p2;
        trunc_ln42_reg_779[40 : 21] <= trunc_ln42_fu_374_p1[40 : 21];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        j_reg_912 <= j_fu_744_p2;
        mask_reg_907 <= mask_fu_739_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        k_3_reg_794 <= {{grp_fu_341_p2[130:129]}};
        tmp_reg_789 <= {{grp_fu_341_p2[140:129]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        lshr_ln_reg_848 <= {{outcos_write_assign_in_in_i_fu_577_p9[64:43]}};
        select_ln265_reg_853 <= select_ln265_fu_622_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln42_reg_807 <= grp_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        p_loc160_fu_138 <= grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        p_loc_fu_142 <= grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_p_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state14_on_subcall_done)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufA_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_im_address0;
    end else begin
        bufA_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_im_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_im_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_im_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_im_address1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_address1;
    end else begin
        bufA_im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufA_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_im_ce0;
    end else begin
        bufA_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_im_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_im_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_im_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_im_ce1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_ce1;
    end else begin
        bufA_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_im_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_d1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_im_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_d1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_im_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_d1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_im_d1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_d1;
    end else begin
        bufA_im_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_im_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_im_we1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_im_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_im_we1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_im_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_im_we1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_im_we1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_im_we1;
    end else begin
        bufA_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufA_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_re_address0;
    end else begin
        bufA_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_re_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_re_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_re_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_re_address1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_address1;
    end else begin
        bufA_re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufA_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufA_re_ce0;
    end else begin
        bufA_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_re_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_re_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_re_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_re_ce1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_ce1;
    end else begin
        bufA_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_re_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_re_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_re_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_re_d1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_d1;
    end else begin
        bufA_re_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufA_re_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufA_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufA_re_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufA_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bufA_re_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_bufA_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufA_re_we1 = grp_applyMixer_hls_3_Pipeline_2_fu_271_bufA_re_we1;
    end else begin
        bufA_re_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufB_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_im_address0;
    end else begin
        bufB_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_im_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_im_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_im_address1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_address1;
    end else begin
        bufB_im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufB_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_im_ce0;
    end else begin
        bufB_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_im_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_im_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_im_ce1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_ce1;
    end else begin
        bufB_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_im_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_d1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_im_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_d1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_im_d1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_d1;
    end else begin
        bufB_im_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_im_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_im_we1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_im_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_im_we1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_im_we1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_im_we1;
    end else begin
        bufB_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufB_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_re_address0;
    end else begin
        bufB_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_re_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_re_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_re_address1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_address1;
    end else begin
        bufB_re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        bufB_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_bufB_re_ce0;
    end else begin
        bufB_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_re_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_re_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_re_ce1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_ce1;
    end else begin
        bufB_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_re_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_re_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_re_d1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_d1;
    end else begin
        bufB_re_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        bufB_re_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_bufB_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bufB_re_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_bufB_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        bufB_re_we1 = grp_applyMixer_hls_3_Pipeline_3_fu_277_bufB_re_we1;
    end else begin
        bufB_re_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_917_ce = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_ce;
    end else begin
        grp_fu_917_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        state_im_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_im_ce0;
    end else begin
        state_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        state_im_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_ce1;
    end else begin
        state_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        state_im_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_we1;
    end else begin
        state_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        state_re_ce0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_re_ce0;
    end else begin
        state_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        state_re_ce1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_ce1;
    end else begin
        state_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        state_re_we1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_we1;
    end else begin
        state_re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln127_fu_631_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln132_fu_669_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln132_1_fu_718_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add41_cast_fu_698_p1 = add41_fu_693_p2;

assign add41_fu_693_p2 = (base_reg_866 + zext_ln132_1_fu_685_p1);

assign add_ln137_fu_724_p2 = (j_1_reg_253 + zext_ln128_reg_871);

assign add_ln42_fu_418_p2 = (shl_ln_fu_411_p3 + mul_ln42_reg_807);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state14_on_subcall_done = ((grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_done == 1'b0) | (grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_done == 1'b0) | (grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_done == 1'b0));
end

assign base_fu_655_p2 = (p_shl_fu_647_p3 - zext_ln127_fu_643_p1);

assign bit_i_fu_702_p2 = 9'd1 << add41_cast_fu_698_p1;

assign bit_j_fu_729_p2 = 32'd1 << add_ln137_fu_724_p2;

assign empty_fu_481_p3 = ((or_ln225_fu_452_p2[0:0] == 1'b1) ? tmp_s_fu_458_p4 : tmp_81_cast_fu_477_p1);

assign grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start = grp_applyMixer_hls_3_Pipeline_2_fu_271_ap_start_reg;

assign grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start = grp_applyMixer_hls_3_Pipeline_3_fu_277_ap_start_reg;

assign grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_ap_start_reg;

assign grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5_fu_307_ap_start_reg;

assign grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_ap_start_reg;

assign grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_ap_start_reg;

assign grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1_fu_262_ap_start_reg;

assign grp_fu_102_p_ce = grp_fu_917_ce;

assign grp_fu_102_p_din0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_din0;

assign grp_fu_102_p_din1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_140_6_fu_319_grp_fu_917_p_din1;

assign grp_fu_336_p0 = grp_fu_336_p00;

assign grp_fu_336_p00 = tmp_reg_789;

assign grp_fu_336_p1 = 66'd15834820630221223725;

assign grp_fu_341_p0 = grp_fu_341_p00;

assign grp_fu_341_p00 = inabs_reg_774;

assign grp_fu_341_p1 = 141'd394048553007286535560068608;

assign icmp_ln127_fu_631_p2 = ((t_fu_134 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln132_1_fu_718_p2 = (($signed(j_1_reg_253) < $signed(32'd3)) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_669_p2 = ((i_reg_216 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln225_1_fu_447_p2 = ((k_3_reg_794 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln225_fu_442_p2 = ((k_3_reg_794 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln248_1_fu_504_p2 = ((k_3_reg_794 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln248_fu_499_p2 = ((k_3_reg_794 == 2'd2) ? 1'b1 : 1'b0);

assign inabs_fu_366_p3 = ((sign0_fu_354_p2[0:0] == 1'b1) ? x_1_fu_346_p3 : sub_ln211_fu_360_p2);

assign j_3_fu_675_p2 = (i_reg_216 + 2'd1);

assign j_fu_744_p2 = (j_1_reg_253 + 32'd1);

assign mask_fu_739_p2 = (trunc_ln137_fu_735_p1 | bit_i_reg_894);

assign or_ln225_fu_452_p2 = (icmp_ln225_fu_442_p2 | icmp_ln225_1_fu_447_p2);

assign or_ln248_fu_509_p2 = (icmp_ln248_1_fu_504_p2 | icmp_ln225_1_reg_822);

assign outcos_write_assign_in_in_i_fu_577_p7 = 'bx;

assign outcos_write_assign_in_in_i_fu_577_p8 = {{icmp_ln248_reg_833}, {icmp_ln225_1_reg_822}};

assign outsin_0_in_in_i_fu_522_p7 = 'bx;

assign outsin_0_in_in_i_fu_522_p8 = {{icmp_ln248_fu_499_p2}, {or_ln248_fu_509_p2}};

assign p_shl_fu_647_p3 = {{t_fu_134}, {2'd0}};

assign select_ln265_fu_622_p3 = ((sign0_reg_769[0:0] == 1'b1) ? tmp_100_reg_843 : tmp_101_fu_612_p4);

assign shl49_fu_708_p2 = 3'd1 << zext_ln132_fu_681_p1;

assign shl_ln_fu_411_p3 = {{trunc_ln42_reg_779}, {25'd0}};

assign sign0_fu_354_p2 = (($signed(beta) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign state_im_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_im_address0;

assign state_im_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_address1;

assign state_im_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_im_d1;

assign state_re_address0 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_116_1_fu_283_state_re_address0;

assign state_re_address1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_address1;

assign state_re_d1 = grp_applyMixer_hls_3_Pipeline_VITIS_LOOP_166_7_fu_293_state_re_d1;

assign sub_ln211_fu_360_p2 = (53'd0 - x_1_fu_346_p3);

assign sub_ln228_fu_436_p2 = (66'd28976077832308491360 - zext_ln42_1_fu_433_p1);

assign sub_ln254_fu_565_p2 = (65'd0 - p_loc160_fu_138);

assign sub_ln261_fu_493_p2 = (65'd0 - p_loc_fu_142);

assign sub_ln266_fu_607_p2 = (42'd0 - trunc_ln1_reg_838);

assign t_2_fu_637_p2 = (t_fu_134 + 2'd1);

assign tmp_101_fu_612_p4 = {{sub_ln266_fu_607_p2[41:20]}};

assign tmp_71_fu_468_p4 = {{add_ln42_reg_812[65:2]}};

assign tmp_81_cast_fu_477_p1 = tmp_71_fu_468_p4;

assign tmp_s_fu_458_p4 = {{sub_ln228_fu_436_p2[65:1]}};

assign trunc_ln128_fu_665_p1 = base_fu_655_p2[2:0];

assign trunc_ln137_fu_735_p1 = bit_j_fu_729_p2[8:0];

assign trunc_ln42_fu_374_p1 = inabs_fu_366_p3[40:0];

assign x_1_fu_346_p3 = {{beta}, {21'd0}};

assign zext_ln127_fu_643_p1 = t_fu_134;

assign zext_ln128_fu_661_p1 = base_fu_655_p2;

assign zext_ln132_1_fu_685_p1 = i_reg_216;

assign zext_ln132_2_fu_689_p1 = j_3_fu_675_p2;

assign zext_ln132_fu_681_p1 = i_reg_216;

assign zext_ln42_1_fu_433_p1 = r_reg_817;

always @ (posedge ap_clk) begin
    inabs_reg_774[20:0] <= 21'b000000000000000000000;
    trunc_ln42_reg_779[20:0] <= 21'b000000000000000000000;
    zext_ln128_reg_871[31:4] <= 28'b0000000000000000000000000000;
end

endmodule //qaoa_kernel_applyMixer_hls_3_s
