// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bufB_re_address0,
        bufB_re_ce0,
        bufB_re_q0,
        bufB_re_address1,
        bufB_re_ce1,
        bufB_re_we1,
        bufB_re_d1,
        bufB_im_address0,
        bufB_im_ce0,
        bufB_im_q0,
        bufB_im_address1,
        bufB_im_ce1,
        bufB_im_we1,
        bufB_im_d1,
        bufA_re_address0,
        bufA_re_ce0,
        bufA_re_q0,
        bufA_re_address1,
        bufA_re_ce1,
        bufA_re_we1,
        bufA_re_d1,
        bufA_im_address0,
        bufA_im_ce0,
        bufA_im_q0,
        bufA_im_address1,
        bufA_im_ce1,
        bufA_im_we1,
        bufA_im_d1,
        state_cur_223131,
        state_next_222129
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] bufB_re_address0;
output   bufB_re_ce0;
input  [31:0] bufB_re_q0;
output  [8:0] bufB_re_address1;
output   bufB_re_ce1;
output   bufB_re_we1;
output  [31:0] bufB_re_d1;
output  [8:0] bufB_im_address0;
output   bufB_im_ce0;
input  [31:0] bufB_im_q0;
output  [8:0] bufB_im_address1;
output   bufB_im_ce1;
output   bufB_im_we1;
output  [31:0] bufB_im_d1;
output  [8:0] bufA_re_address0;
output   bufA_re_ce0;
input  [31:0] bufA_re_q0;
output  [8:0] bufA_re_address1;
output   bufA_re_ce1;
output   bufA_re_we1;
output  [31:0] bufA_re_d1;
output  [8:0] bufA_im_address0;
output   bufA_im_ce0;
input  [31:0] bufA_im_q0;
output  [8:0] bufA_im_address1;
output   bufA_im_ce1;
output   bufA_im_we1;
output  [31:0] bufA_im_d1;
input  [0:0] state_cur_223131;
input  [0:0] state_next_222129;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln134_fu_140_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] state_next_222129_read_reg_190;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] bufB_re_addr_reg_203;
reg   [8:0] bufB_im_addr_reg_209;
reg   [8:0] bufA_re_addr_reg_215;
reg   [8:0] bufA_im_addr_reg_221;
wire   [63:0] zext_ln134_fu_152_p1;
wire    ap_block_pp0_stage0;
reg   [9:0] k_fu_48;
wire   [9:0] add_ln134_fu_146_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_k_2;
reg    bufB_re_ce0_local;
reg    bufB_re_we1_local;
wire   [31:0] empty_fu_165_p3;
reg    bufB_re_ce1_local;
reg    bufB_im_ce0_local;
reg    bufB_im_we1_local;
wire   [31:0] empty_60_fu_174_p3;
reg    bufB_im_ce1_local;
reg    bufA_re_ce0_local;
reg    bufA_re_we1_local;
reg    bufA_re_ce1_local;
reg    bufA_im_ce0_local;
reg    bufA_im_we1_local;
reg    bufA_im_ce1_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_48 = 10'd0;
#0 ap_done_reg = 1'b0;
end

qaoa_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln134_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_48 <= add_ln134_fu_146_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_48 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_im_addr_reg_221 <= zext_ln134_fu_152_p1;
        bufA_re_addr_reg_215 <= zext_ln134_fu_152_p1;
        bufB_im_addr_reg_209 <= zext_ln134_fu_152_p1;
        bufB_re_addr_reg_203 <= zext_ln134_fu_152_p1;
    end
end

always @ (*) begin
    if (((icmp_ln134_fu_140_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_2 = 10'd0;
    end else begin
        ap_sig_allocacmp_k_2 = k_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_im_ce0_local = 1'b1;
    end else begin
        bufA_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_im_ce1_local = 1'b1;
    end else begin
        bufA_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_190 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_im_we1_local = 1'b1;
    end else begin
        bufA_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_re_ce0_local = 1'b1;
    end else begin
        bufA_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_re_ce1_local = 1'b1;
    end else begin
        bufA_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_190 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufA_re_we1_local = 1'b1;
    end else begin
        bufA_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufB_im_ce0_local = 1'b1;
    end else begin
        bufB_im_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufB_im_ce1_local = 1'b1;
    end else begin
        bufB_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_190 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufB_im_we1_local = 1'b1;
    end else begin
        bufB_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufB_re_ce0_local = 1'b1;
    end else begin
        bufB_re_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufB_re_ce1_local = 1'b1;
    end else begin
        bufB_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((state_next_222129_read_reg_190 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufB_re_we1_local = 1'b1;
    end else begin
        bufB_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln134_fu_146_p2 = (ap_sig_allocacmp_k_2 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bufA_im_address0 = zext_ln134_fu_152_p1;

assign bufA_im_address1 = bufA_im_addr_reg_221;

assign bufA_im_ce0 = bufA_im_ce0_local;

assign bufA_im_ce1 = bufA_im_ce1_local;

assign bufA_im_d1 = empty_60_fu_174_p3;

assign bufA_im_we1 = bufA_im_we1_local;

assign bufA_re_address0 = zext_ln134_fu_152_p1;

assign bufA_re_address1 = bufA_re_addr_reg_215;

assign bufA_re_ce0 = bufA_re_ce0_local;

assign bufA_re_ce1 = bufA_re_ce1_local;

assign bufA_re_d1 = empty_fu_165_p3;

assign bufA_re_we1 = bufA_re_we1_local;

assign bufB_im_address0 = zext_ln134_fu_152_p1;

assign bufB_im_address1 = bufB_im_addr_reg_209;

assign bufB_im_ce0 = bufB_im_ce0_local;

assign bufB_im_ce1 = bufB_im_ce1_local;

assign bufB_im_d1 = empty_60_fu_174_p3;

assign bufB_im_we1 = bufB_im_we1_local;

assign bufB_re_address0 = zext_ln134_fu_152_p1;

assign bufB_re_address1 = bufB_re_addr_reg_203;

assign bufB_re_ce0 = bufB_re_ce0_local;

assign bufB_re_ce1 = bufB_re_ce1_local;

assign bufB_re_d1 = empty_fu_165_p3;

assign bufB_re_we1 = bufB_re_we1_local;

assign empty_60_fu_174_p3 = ((state_cur_223131[0:0] == 1'b1) ? bufB_im_q0 : bufA_im_q0);

assign empty_fu_165_p3 = ((state_cur_223131[0:0] == 1'b1) ? bufB_re_q0 : bufA_re_q0);

assign icmp_ln134_fu_140_p2 = ((ap_sig_allocacmp_k_2 == 10'd512) ? 1'b1 : 1'b0);

assign state_next_222129_read_reg_190 = state_next_222129;

assign zext_ln134_fu_152_p1 = ap_sig_allocacmp_k_2;

endmodule //qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_134_5
