// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="qaoa_kernel_qaoa_kernel,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=15.928667,HLS_SYN_LAT=182998,HLS_SYN_TPT=182998,HLS_SYN_MEM=18,HLS_SYN_DSP=0,HLS_SYN_FF=14394,HLS_SYN_LUT=29346,HLS_VERSION=2024_2}" *)

module qaoa_kernel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] gamma;
wire   [31:0] beta;
wire   [0:0] get_best_state;
wire   [31:0] d_q0;
wire    Block_entry_state_re_wr_d_rd_proc_U0_ap_start;
wire    Block_entry_state_re_wr_d_rd_proc_U0_ap_done;
wire    Block_entry_state_re_wr_d_rd_proc_U0_ap_continue;
wire    Block_entry_state_re_wr_d_rd_proc_U0_ap_idle;
wire    Block_entry_state_re_wr_d_rd_proc_U0_ap_ready;
wire   [3:0] Block_entry_state_re_wr_d_rd_proc_U0_d_address0;
wire    Block_entry_state_re_wr_d_rd_proc_U0_d_ce0;
wire   [31:0] Block_entry_state_re_wr_d_rd_proc_U0_best_state;
wire    Block_entry_state_re_wr_d_rd_proc_U0_best_state_ap_vld;
wire   [31:0] Block_entry_state_re_wr_d_rd_proc_U0_ap_return;
wire    ap_channel_done_retval_0_loc_channel1;
wire    retval_0_loc_channel1_full_n;
reg    ap_sync_reg_channel_write_retval_0_loc_channel1;
wire    ap_sync_channel_write_retval_0_loc_channel1;
wire    ap_sync_continue;
wire    Block_entry_proc_proc_U0_ap_start;
wire    Block_entry_proc_proc_U0_ap_done;
wire    Block_entry_proc_proc_U0_ap_continue;
wire    Block_entry_proc_proc_U0_ap_idle;
wire    Block_entry_proc_proc_U0_ap_ready;
wire   [31:0] Block_entry_proc_proc_U0_ap_return;
wire   [31:0] retval_0_loc_channel1_dout;
wire    retval_0_loc_channel1_empty_n;
wire   [2:0] retval_0_loc_channel1_num_data_valid;
wire   [2:0] retval_0_loc_channel1_fifo_cap;
wire    ap_sync_done;
wire    ap_ce_reg;
wire   [31:0] ap_return;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_retval_0_loc_channel1 = 1'b0;
end

qaoa_kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(Block_entry_proc_proc_U0_ap_return),
    .gamma(gamma),
    .beta(beta),
    .get_best_state(get_best_state),
    .best_state(Block_entry_state_re_wr_d_rd_proc_U0_best_state),
    .best_state_ap_vld(Block_entry_state_re_wr_d_rd_proc_U0_best_state_ap_vld),
    .d_address0(Block_entry_state_re_wr_d_rd_proc_U0_d_address0),
    .d_ce0(Block_entry_state_re_wr_d_rd_proc_U0_d_ce0),
    .d_q0(d_q0)
);

qaoa_kernel_Block_entry_state_re_wr_d_rd_proc Block_entry_state_re_wr_d_rd_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_state_re_wr_d_rd_proc_U0_ap_start),
    .ap_done(Block_entry_state_re_wr_d_rd_proc_U0_ap_done),
    .ap_continue(Block_entry_state_re_wr_d_rd_proc_U0_ap_continue),
    .ap_idle(Block_entry_state_re_wr_d_rd_proc_U0_ap_idle),
    .ap_ready(Block_entry_state_re_wr_d_rd_proc_U0_ap_ready),
    .d_address0(Block_entry_state_re_wr_d_rd_proc_U0_d_address0),
    .d_ce0(Block_entry_state_re_wr_d_rd_proc_U0_d_ce0),
    .d_q0(d_q0),
    .gamma(gamma),
    .beta(beta),
    .get_best_state(get_best_state),
    .best_state(Block_entry_state_re_wr_d_rd_proc_U0_best_state),
    .best_state_ap_vld(Block_entry_state_re_wr_d_rd_proc_U0_best_state_ap_vld),
    .ap_return(Block_entry_state_re_wr_d_rd_proc_U0_ap_return)
);

qaoa_kernel_Block_entry_proc_proc Block_entry_proc_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_proc_proc_U0_ap_start),
    .ap_done(Block_entry_proc_proc_U0_ap_done),
    .ap_continue(Block_entry_proc_proc_U0_ap_continue),
    .ap_idle(Block_entry_proc_proc_U0_ap_idle),
    .ap_ready(Block_entry_proc_proc_U0_ap_ready),
    .p_read(retval_0_loc_channel1_dout),
    .ap_return(Block_entry_proc_proc_U0_ap_return)
);

qaoa_kernel_fifo_w32_d2_S retval_0_loc_channel1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_state_re_wr_d_rd_proc_U0_ap_return),
    .if_full_n(retval_0_loc_channel1_full_n),
    .if_write(ap_channel_done_retval_0_loc_channel1),
    .if_dout(retval_0_loc_channel1_dout),
    .if_empty_n(retval_0_loc_channel1_empty_n),
    .if_read(Block_entry_proc_proc_U0_ap_ready),
    .if_num_data_valid(retval_0_loc_channel1_num_data_valid),
    .if_fifo_cap(retval_0_loc_channel1_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_retval_0_loc_channel1 <= 1'b0;
    end else begin
        if (((Block_entry_state_re_wr_d_rd_proc_U0_ap_done & Block_entry_state_re_wr_d_rd_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_retval_0_loc_channel1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_retval_0_loc_channel1 <= ap_sync_channel_write_retval_0_loc_channel1;
        end
    end
end

assign Block_entry_proc_proc_U0_ap_continue = ap_sync_done;

assign Block_entry_proc_proc_U0_ap_start = retval_0_loc_channel1_empty_n;

assign Block_entry_state_re_wr_d_rd_proc_U0_ap_continue = (ap_sync_continue & ap_sync_channel_write_retval_0_loc_channel1);

assign Block_entry_state_re_wr_d_rd_proc_U0_ap_start = ap_start;

assign ap_channel_done_retval_0_loc_channel1 = ((ap_sync_reg_channel_write_retval_0_loc_channel1 ^ 1'b1) & Block_entry_state_re_wr_d_rd_proc_U0_ap_done);

assign ap_done = ap_sync_done;

assign ap_idle = ((retval_0_loc_channel1_empty_n ^ 1'b1) & Block_entry_state_re_wr_d_rd_proc_U0_ap_idle & Block_entry_proc_proc_U0_ap_idle);

assign ap_ready = Block_entry_state_re_wr_d_rd_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_retval_0_loc_channel1 = ((retval_0_loc_channel1_full_n & ap_channel_done_retval_0_loc_channel1) | ap_sync_reg_channel_write_retval_0_loc_channel1);

assign ap_sync_continue = ap_sync_done;

assign ap_sync_done = (Block_entry_state_re_wr_d_rd_proc_U0_ap_done & Block_entry_proc_proc_U0_ap_done);

endmodule //qaoa_kernel
