// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_expectation_cost_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_re_address0,
        state_re_ce0,
        state_re_q0,
        state_im_address0,
        state_im_ce0,
        state_im_q0,
        d_address0,
        d_ce0,
        d_q0,
        ap_return_0,
        ap_return_1,
        grp_fu_828_p_din0,
        grp_fu_828_p_din1,
        grp_fu_828_p_dout0,
        grp_fu_828_p_ce
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] state_re_address0;
output   state_re_ce0;
input  [31:0] state_re_q0;
output  [8:0] state_im_address0;
output   state_im_ce0;
input  [31:0] state_im_q0;
output  [3:0] d_address0;
output   d_ce0;
input  [31:0] d_q0;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] grp_fu_828_p_din0;
output  [31:0] grp_fu_828_p_din1;
input  [51:0] grp_fu_828_p_dout0;
output   grp_fu_828_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg   [31:0] d_load_reg_204;
wire    ap_CS_fsm_state3;
reg   [31:0] d_load_1_reg_214;
wire    ap_CS_fsm_state4;
reg   [31:0] d_load_2_reg_224;
wire    ap_CS_fsm_state5;
reg   [31:0] d_load_3_reg_234;
wire    ap_CS_fsm_state6;
reg   [31:0] d_load_4_reg_244;
wire    ap_CS_fsm_state7;
reg   [31:0] d_load_5_reg_254;
wire    ap_CS_fsm_state8;
reg   [31:0] d_load_6_reg_264;
wire    ap_CS_fsm_state9;
reg   [31:0] d_load_7_reg_274;
reg   [31:0] d_load_8_reg_279;
wire    ap_CS_fsm_state10;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_idle;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_ready;
wire   [8:0] grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_address0;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_ce0;
wire   [8:0] grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_address0;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_ce0;
wire   [31:0] grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out_ap_vld;
wire   [31:0] grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out_ap_vld;
wire  signed [31:0] grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din0;
wire  signed [31:0] grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din1;
wire    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce;
reg    grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    d_ce0_local;
reg   [3:0] d_address0_local;
reg    grp_fu_284_ce;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg = 1'b0;
end

qaoa_kernel_expectation_cost_3_Pipeline_VITIS_LOOP_177_1 grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start),
    .ap_done(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done),
    .ap_idle(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_idle),
    .ap_ready(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_ready),
    .state_re_address0(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_address0),
    .state_re_ce0(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_ce0),
    .state_re_q0(state_re_q0),
    .state_im_address0(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_address0),
    .state_im_ce0(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_ce0),
    .state_im_q0(state_im_q0),
    .d_load(d_load_reg_204),
    .d_load_1(d_load_1_reg_214),
    .d_load_2(d_load_2_reg_224),
    .d_load_3(d_load_3_reg_234),
    .d_load_4(d_load_4_reg_244),
    .d_load_5(d_load_5_reg_254),
    .d_load_6(d_load_6_reg_264),
    .d_load_7(d_load_7_reg_274),
    .d_load_8(d_load_8_reg_279),
    .result_out(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out),
    .result_out_ap_vld(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out_ap_vld),
    .argmax_out(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out),
    .argmax_out_ap_vld(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out_ap_vld),
    .grp_fu_284_p_din0(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din0),
    .grp_fu_284_p_din1(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din1),
    .grp_fu_284_p_dout0(grp_fu_828_p_dout0),
    .grp_fu_284_p_ce(grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg <= 1'b1;
        end else if ((grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_ready == 1'b1)) begin
            grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        d_load_1_reg_214 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        d_load_2_reg_224 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        d_load_3_reg_234 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_load_4_reg_244 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        d_load_5_reg_254 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        d_load_6_reg_264 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        d_load_7_reg_274 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_load_8_reg_279 <= d_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        d_load_reg_204 <= d_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        d_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        d_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        d_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_address0_local = 64'd0;
    end else begin
        d_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        d_ce0_local = 1'b1;
    end else begin
        d_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_284_ce = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_ce;
    end else begin
        grp_fu_284_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_result_out;

assign ap_return_1 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_argmax_out;

assign d_address0 = d_address0_local;

assign d_ce0 = d_ce0_local;

assign grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_ap_start_reg;

assign grp_fu_828_p_ce = grp_fu_284_ce;

assign grp_fu_828_p_din0 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din0;

assign grp_fu_828_p_din1 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_grp_fu_284_p_din1;

assign state_im_address0 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_address0;

assign state_im_ce0 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_im_ce0;

assign state_re_address0 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_address0;

assign state_re_ce0 = grp_expectation_cost_3_Pipeline_VITIS_LOOP_177_1_fu_144_state_re_ce0;

endmodule //qaoa_kernel_expectation_cost_3_s
