// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_qaoaStep_hls_3_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_re_address0,
        state_re_ce0,
        state_re_q0,
        state_re_address1,
        state_re_ce1,
        state_re_we1,
        state_re_d1,
        state_im_address0,
        state_im_ce0,
        state_im_q0,
        state_im_address1,
        state_im_ce1,
        state_im_we1,
        state_im_d1,
        d_address0,
        d_ce0,
        d_q0,
        gamma_0_0_val,
        beta_0_0_val,
        grp_fu_828_p_din0,
        grp_fu_828_p_din1,
        grp_fu_828_p_dout0,
        grp_fu_828_p_ce
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] state_re_address0;
output   state_re_ce0;
input  [31:0] state_re_q0;
output  [8:0] state_re_address1;
output   state_re_ce1;
output   state_re_we1;
output  [31:0] state_re_d1;
output  [8:0] state_im_address0;
output   state_im_ce0;
input  [31:0] state_im_q0;
output  [8:0] state_im_address1;
output   state_im_ce1;
output   state_im_we1;
output  [31:0] state_im_d1;
output  [3:0] d_address0;
output   d_ce0;
input  [31:0] d_q0;
input  [31:0] gamma_0_0_val;
input  [31:0] beta_0_0_val;
output  [31:0] grp_fu_828_p_din0;
output  [31:0] grp_fu_828_p_din1;
input  [51:0] grp_fu_828_p_dout0;
output   grp_fu_828_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] state_re_address0;
reg state_re_ce0;
reg[8:0] state_re_address1;
reg state_re_ce1;
reg state_re_we1;
reg[31:0] state_re_d1;
reg[8:0] state_im_address0;
reg state_im_ce0;
reg[8:0] state_im_address1;
reg state_im_ce1;
reg state_im_we1;
reg[31:0] state_im_d1;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    grp_build_feasible_superposition_3_s_fu_58_ap_start;
wire    grp_build_feasible_superposition_3_s_fu_58_ap_done;
wire    grp_build_feasible_superposition_3_s_fu_58_ap_idle;
wire    grp_build_feasible_superposition_3_s_fu_58_ap_ready;
wire   [8:0] grp_build_feasible_superposition_3_s_fu_58_state_re_address1;
wire    grp_build_feasible_superposition_3_s_fu_58_state_re_ce1;
wire    grp_build_feasible_superposition_3_s_fu_58_state_re_we1;
wire   [31:0] grp_build_feasible_superposition_3_s_fu_58_state_re_d1;
wire   [8:0] grp_build_feasible_superposition_3_s_fu_58_state_im_address1;
wire    grp_build_feasible_superposition_3_s_fu_58_state_im_ce1;
wire    grp_build_feasible_superposition_3_s_fu_58_state_im_we1;
wire   [31:0] grp_build_feasible_superposition_3_s_fu_58_state_im_d1;
wire    grp_applyCost_hls_3_s_fu_66_ap_start;
wire    grp_applyCost_hls_3_s_fu_66_ap_done;
wire    grp_applyCost_hls_3_s_fu_66_ap_idle;
wire    grp_applyCost_hls_3_s_fu_66_ap_ready;
wire   [8:0] grp_applyCost_hls_3_s_fu_66_state_re_address0;
wire    grp_applyCost_hls_3_s_fu_66_state_re_ce0;
wire   [8:0] grp_applyCost_hls_3_s_fu_66_state_re_address1;
wire    grp_applyCost_hls_3_s_fu_66_state_re_ce1;
wire    grp_applyCost_hls_3_s_fu_66_state_re_we1;
wire   [31:0] grp_applyCost_hls_3_s_fu_66_state_re_d1;
wire   [8:0] grp_applyCost_hls_3_s_fu_66_state_im_address0;
wire    grp_applyCost_hls_3_s_fu_66_state_im_ce0;
wire   [3:0] grp_applyCost_hls_3_s_fu_66_d_address0;
wire    grp_applyCost_hls_3_s_fu_66_d_ce0;
wire  signed [31:0] grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0;
wire  signed [21:0] grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1;
wire    grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce;
wire  signed [31:0] grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din0;
wire  signed [31:0] grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din1;
wire    grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce;
wire    grp_applyMixer_hls_3_s_fu_80_ap_start;
wire    grp_applyMixer_hls_3_s_fu_80_ap_done;
wire    grp_applyMixer_hls_3_s_fu_80_ap_idle;
wire    grp_applyMixer_hls_3_s_fu_80_ap_ready;
wire   [8:0] grp_applyMixer_hls_3_s_fu_80_state_re_address0;
wire    grp_applyMixer_hls_3_s_fu_80_state_re_ce0;
wire   [8:0] grp_applyMixer_hls_3_s_fu_80_state_re_address1;
wire    grp_applyMixer_hls_3_s_fu_80_state_re_ce1;
wire    grp_applyMixer_hls_3_s_fu_80_state_re_we1;
wire   [31:0] grp_applyMixer_hls_3_s_fu_80_state_re_d1;
wire   [8:0] grp_applyMixer_hls_3_s_fu_80_state_im_address0;
wire    grp_applyMixer_hls_3_s_fu_80_state_im_ce0;
wire   [8:0] grp_applyMixer_hls_3_s_fu_80_state_im_address1;
wire    grp_applyMixer_hls_3_s_fu_80_state_im_ce1;
wire    grp_applyMixer_hls_3_s_fu_80_state_im_we1;
wire   [31:0] grp_applyMixer_hls_3_s_fu_80_state_im_d1;
wire  signed [31:0] grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0;
wire  signed [21:0] grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1;
wire    grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce;
reg    grp_build_feasible_superposition_3_s_fu_58_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_applyCost_hls_3_s_fu_66_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_applyMixer_hls_3_s_fu_80_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [51:0] grp_fu_102_p2;
reg  signed [31:0] grp_fu_102_p0;
reg  signed [21:0] grp_fu_102_p1;
reg    grp_fu_102_ce;
reg    grp_fu_106_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_build_feasible_superposition_3_s_fu_58_ap_start_reg = 1'b0;
#0 grp_applyCost_hls_3_s_fu_66_ap_start_reg = 1'b0;
#0 grp_applyMixer_hls_3_s_fu_80_ap_start_reg = 1'b0;
end

qaoa_kernel_build_feasible_superposition_3_s grp_build_feasible_superposition_3_s_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_build_feasible_superposition_3_s_fu_58_ap_start),
    .ap_done(grp_build_feasible_superposition_3_s_fu_58_ap_done),
    .ap_idle(grp_build_feasible_superposition_3_s_fu_58_ap_idle),
    .ap_ready(grp_build_feasible_superposition_3_s_fu_58_ap_ready),
    .state_re_address1(grp_build_feasible_superposition_3_s_fu_58_state_re_address1),
    .state_re_ce1(grp_build_feasible_superposition_3_s_fu_58_state_re_ce1),
    .state_re_we1(grp_build_feasible_superposition_3_s_fu_58_state_re_we1),
    .state_re_d1(grp_build_feasible_superposition_3_s_fu_58_state_re_d1),
    .state_im_address1(grp_build_feasible_superposition_3_s_fu_58_state_im_address1),
    .state_im_ce1(grp_build_feasible_superposition_3_s_fu_58_state_im_ce1),
    .state_im_we1(grp_build_feasible_superposition_3_s_fu_58_state_im_we1),
    .state_im_d1(grp_build_feasible_superposition_3_s_fu_58_state_im_d1)
);

qaoa_kernel_applyCost_hls_3_s grp_applyCost_hls_3_s_fu_66(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyCost_hls_3_s_fu_66_ap_start),
    .ap_done(grp_applyCost_hls_3_s_fu_66_ap_done),
    .ap_idle(grp_applyCost_hls_3_s_fu_66_ap_idle),
    .ap_ready(grp_applyCost_hls_3_s_fu_66_ap_ready),
    .state_re_address0(grp_applyCost_hls_3_s_fu_66_state_re_address0),
    .state_re_ce0(grp_applyCost_hls_3_s_fu_66_state_re_ce0),
    .state_re_q0(state_re_q0),
    .state_re_address1(grp_applyCost_hls_3_s_fu_66_state_re_address1),
    .state_re_ce1(grp_applyCost_hls_3_s_fu_66_state_re_ce1),
    .state_re_we1(grp_applyCost_hls_3_s_fu_66_state_re_we1),
    .state_re_d1(grp_applyCost_hls_3_s_fu_66_state_re_d1),
    .state_im_address0(grp_applyCost_hls_3_s_fu_66_state_im_address0),
    .state_im_ce0(grp_applyCost_hls_3_s_fu_66_state_im_ce0),
    .state_im_q0(state_im_q0),
    .d_address0(grp_applyCost_hls_3_s_fu_66_d_address0),
    .d_ce0(grp_applyCost_hls_3_s_fu_66_d_ce0),
    .d_q0(d_q0),
    .gamma(gamma_0_0_val),
    .grp_fu_102_p_din0(grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0),
    .grp_fu_102_p_din1(grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1),
    .grp_fu_102_p_dout0(grp_fu_102_p2),
    .grp_fu_102_p_ce(grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce),
    .grp_fu_106_p_din0(grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din0),
    .grp_fu_106_p_din1(grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din1),
    .grp_fu_106_p_dout0(grp_fu_828_p_dout0),
    .grp_fu_106_p_ce(grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce)
);

qaoa_kernel_applyMixer_hls_3_s grp_applyMixer_hls_3_s_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_applyMixer_hls_3_s_fu_80_ap_start),
    .ap_done(grp_applyMixer_hls_3_s_fu_80_ap_done),
    .ap_idle(grp_applyMixer_hls_3_s_fu_80_ap_idle),
    .ap_ready(grp_applyMixer_hls_3_s_fu_80_ap_ready),
    .state_re_address0(grp_applyMixer_hls_3_s_fu_80_state_re_address0),
    .state_re_ce0(grp_applyMixer_hls_3_s_fu_80_state_re_ce0),
    .state_re_q0(state_re_q0),
    .state_re_address1(grp_applyMixer_hls_3_s_fu_80_state_re_address1),
    .state_re_ce1(grp_applyMixer_hls_3_s_fu_80_state_re_ce1),
    .state_re_we1(grp_applyMixer_hls_3_s_fu_80_state_re_we1),
    .state_re_d1(grp_applyMixer_hls_3_s_fu_80_state_re_d1),
    .state_im_address0(grp_applyMixer_hls_3_s_fu_80_state_im_address0),
    .state_im_ce0(grp_applyMixer_hls_3_s_fu_80_state_im_ce0),
    .state_im_q0(state_im_q0),
    .state_im_address1(grp_applyMixer_hls_3_s_fu_80_state_im_address1),
    .state_im_ce1(grp_applyMixer_hls_3_s_fu_80_state_im_ce1),
    .state_im_we1(grp_applyMixer_hls_3_s_fu_80_state_im_we1),
    .state_im_d1(grp_applyMixer_hls_3_s_fu_80_state_im_d1),
    .beta(beta_0_0_val),
    .grp_fu_102_p_din0(grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0),
    .grp_fu_102_p_din1(grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1),
    .grp_fu_102_p_dout0(grp_fu_102_p2),
    .grp_fu_102_p_ce(grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce)
);

qaoa_kernel_mul_32s_22s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 52 ))
mul_32s_22s_52_2_1_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_102_p0),
    .din1(grp_fu_102_p1),
    .ce(grp_fu_102_ce),
    .dout(grp_fu_102_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyCost_hls_3_s_fu_66_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_applyCost_hls_3_s_fu_66_ap_start_reg <= 1'b1;
        end else if ((grp_applyCost_hls_3_s_fu_66_ap_ready == 1'b1)) begin
            grp_applyCost_hls_3_s_fu_66_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_applyMixer_hls_3_s_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_applyMixer_hls_3_s_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_applyMixer_hls_3_s_fu_80_ap_ready == 1'b1)) begin
            grp_applyMixer_hls_3_s_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_build_feasible_superposition_3_s_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_build_feasible_superposition_3_s_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_build_feasible_superposition_3_s_fu_58_ap_ready == 1'b1)) begin
            grp_build_feasible_superposition_3_s_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_build_feasible_superposition_3_s_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_applyCost_hls_3_s_fu_66_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_applyMixer_hls_3_s_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state6) & (grp_applyMixer_hls_3_s_fu_80_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_applyMixer_hls_3_s_fu_80_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_102_ce = grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_102_ce = grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_ce;
    end else begin
        grp_fu_102_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_102_p0 = grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_102_p0 = grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din0;
    end else begin
        grp_fu_102_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_102_p1 = grp_applyMixer_hls_3_s_fu_80_grp_fu_102_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_102_p1 = grp_applyCost_hls_3_s_fu_66_grp_fu_102_p_din1;
    end else begin
        grp_fu_102_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_106_ce = grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_ce;
    end else begin
        grp_fu_106_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_im_address0 = grp_applyMixer_hls_3_s_fu_80_state_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_im_address0 = grp_applyCost_hls_3_s_fu_66_state_im_address0;
    end else begin
        state_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_im_address1 = grp_applyMixer_hls_3_s_fu_80_state_im_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_im_address1 = grp_build_feasible_superposition_3_s_fu_58_state_im_address1;
    end else begin
        state_im_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_im_ce0 = grp_applyMixer_hls_3_s_fu_80_state_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_im_ce0 = grp_applyCost_hls_3_s_fu_66_state_im_ce0;
    end else begin
        state_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_im_ce1 = grp_applyMixer_hls_3_s_fu_80_state_im_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_im_ce1 = grp_build_feasible_superposition_3_s_fu_58_state_im_ce1;
    end else begin
        state_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_im_d1 = grp_applyMixer_hls_3_s_fu_80_state_im_d1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_im_d1 = grp_build_feasible_superposition_3_s_fu_58_state_im_d1;
    end else begin
        state_im_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_im_we1 = grp_applyMixer_hls_3_s_fu_80_state_im_we1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_im_we1 = grp_build_feasible_superposition_3_s_fu_58_state_im_we1;
    end else begin
        state_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_re_address0 = grp_applyMixer_hls_3_s_fu_80_state_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_re_address0 = grp_applyCost_hls_3_s_fu_66_state_re_address0;
    end else begin
        state_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_re_address1 = grp_applyMixer_hls_3_s_fu_80_state_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_re_address1 = grp_applyCost_hls_3_s_fu_66_state_re_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_re_address1 = grp_build_feasible_superposition_3_s_fu_58_state_re_address1;
    end else begin
        state_re_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_re_ce0 = grp_applyMixer_hls_3_s_fu_80_state_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_re_ce0 = grp_applyCost_hls_3_s_fu_66_state_re_ce0;
    end else begin
        state_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_re_ce1 = grp_applyMixer_hls_3_s_fu_80_state_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_re_ce1 = grp_applyCost_hls_3_s_fu_66_state_re_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_re_ce1 = grp_build_feasible_superposition_3_s_fu_58_state_re_ce1;
    end else begin
        state_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_re_d1 = grp_applyMixer_hls_3_s_fu_80_state_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_re_d1 = grp_applyCost_hls_3_s_fu_66_state_re_d1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_re_d1 = grp_build_feasible_superposition_3_s_fu_58_state_re_d1;
    end else begin
        state_re_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_re_we1 = grp_applyMixer_hls_3_s_fu_80_state_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_re_we1 = grp_applyCost_hls_3_s_fu_66_state_re_we1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_re_we1 = grp_build_feasible_superposition_3_s_fu_58_state_re_we1;
    end else begin
        state_re_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_build_feasible_superposition_3_s_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_applyCost_hls_3_s_fu_66_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_applyMixer_hls_3_s_fu_80_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign d_address0 = grp_applyCost_hls_3_s_fu_66_d_address0;

assign d_ce0 = grp_applyCost_hls_3_s_fu_66_d_ce0;

assign grp_applyCost_hls_3_s_fu_66_ap_start = grp_applyCost_hls_3_s_fu_66_ap_start_reg;

assign grp_applyMixer_hls_3_s_fu_80_ap_start = grp_applyMixer_hls_3_s_fu_80_ap_start_reg;

assign grp_build_feasible_superposition_3_s_fu_58_ap_start = grp_build_feasible_superposition_3_s_fu_58_ap_start_reg;

assign grp_fu_828_p_ce = grp_fu_106_ce;

assign grp_fu_828_p_din0 = grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din0;

assign grp_fu_828_p_din1 = grp_applyCost_hls_3_s_fu_66_grp_fu_106_p_din1;

endmodule //qaoa_kernel_qaoaStep_hls_3_1_s
