domain_path: /home/master25/mae26/s.kim/RP/QAOA-TSP-supaero-mae-reasearch/vitis_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /usr/local/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
