// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_build_feasible_superposition_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_re_address1,
        state_re_ce1,
        state_re_we1,
        state_re_d1,
        state_im_address1,
        state_im_ce1,
        state_im_we1,
        state_im_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] state_re_address1;
output   state_re_ce1;
output   state_re_we1;
output  [31:0] state_re_d1;
output  [8:0] state_im_address1;
output   state_im_ce1;
output   state_im_we1;
output  [31:0] state_im_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_107_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln60_fu_119_p1;
reg   [63:0] zext_ln60_reg_325;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln73_fu_168_p2;
reg   [0:0] icmp_ln73_reg_330;
wire   [0:0] icmp_ln73_1_fu_222_p2;
reg   [0:0] icmp_ln73_1_reg_335;
wire   [0:0] icmp_ln73_2_fu_276_p2;
reg   [0:0] icmp_ln73_2_reg_340;
wire    ap_block_pp0_stage0;
reg   [9:0] s_fu_60;
wire   [9:0] add_ln60_fu_113_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_s_2;
reg    state_im_we1_local;
reg    state_im_ce1_local;
reg    state_re_we1_local;
wire   [31:0] zext_ln61_fu_310_p1;
reg    state_re_ce1_local;
wire   [0:0] tmp_fu_128_p3;
wire   [0:0] trunc_ln103_fu_124_p1;
wire   [0:0] tmp_93_fu_144_p3;
wire   [1:0] zext_ln71_fu_140_p1;
wire   [1:0] zext_ln71_2_fu_152_p1;
wire   [1:0] add_ln71_fu_156_p2;
wire   [1:0] zext_ln71_1_fu_136_p1;
wire   [1:0] ones_fu_162_p2;
wire   [0:0] tmp_94_fu_174_p3;
wire   [0:0] tmp_95_fu_186_p3;
wire   [0:0] tmp_96_fu_198_p3;
wire   [1:0] zext_ln71_4_fu_194_p1;
wire   [1:0] zext_ln71_5_fu_206_p1;
wire   [1:0] add_ln71_2_fu_210_p2;
wire   [1:0] zext_ln71_3_fu_182_p1;
wire   [1:0] ones_1_fu_216_p2;
wire   [0:0] tmp_97_fu_228_p3;
wire   [0:0] tmp_98_fu_240_p3;
wire   [0:0] tmp_99_fu_252_p3;
wire   [1:0] zext_ln71_7_fu_248_p1;
wire   [1:0] zext_ln71_8_fu_260_p1;
wire   [1:0] add_ln71_4_fu_264_p2;
wire   [1:0] zext_ln71_6_fu_236_p1;
wire   [1:0] ones_2_fu_270_p2;
wire   [0:0] and_ln73_fu_294_p2;
wire   [16:0] phitmp_fu_287_p3;
wire   [16:0] phi_ln61_fu_298_p3;
wire  signed [17:0] sext_ln61_fu_306_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 s_fu_60 = 10'd0;
#0 ap_done_reg = 1'b0;
end

qaoa_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_107_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            s_fu_60 <= add_ln60_fu_113_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            s_fu_60 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln73_1_reg_335 <= icmp_ln73_1_fu_222_p2;
        icmp_ln73_2_reg_340 <= icmp_ln73_2_fu_276_p2;
        icmp_ln73_reg_330 <= icmp_ln73_fu_168_p2;
        zext_ln60_reg_325[9 : 0] <= zext_ln60_fu_119_p1[9 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_107_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s_2 = 10'd0;
    end else begin
        ap_sig_allocacmp_s_2 = s_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_im_ce1_local = 1'b1;
    end else begin
        state_im_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_107_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_im_we1_local = 1'b1;
    end else begin
        state_im_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_re_ce1_local = 1'b1;
    end else begin
        state_re_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_re_we1_local = 1'b1;
    end else begin
        state_re_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_fu_113_p2 = (ap_sig_allocacmp_s_2 + 10'd1);

assign add_ln71_2_fu_210_p2 = (zext_ln71_4_fu_194_p1 + zext_ln71_5_fu_206_p1);

assign add_ln71_4_fu_264_p2 = (zext_ln71_7_fu_248_p1 + zext_ln71_8_fu_260_p1);

assign add_ln71_fu_156_p2 = (zext_ln71_fu_140_p1 + zext_ln71_2_fu_152_p1);

assign and_ln73_fu_294_p2 = (icmp_ln73_reg_330 & icmp_ln73_1_reg_335);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln60_fu_107_p2 = ((ap_sig_allocacmp_s_2 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln73_1_fu_222_p2 = ((ones_1_fu_216_p2 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln73_2_fu_276_p2 = ((ones_2_fu_270_p2 != 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_168_p2 = ((ones_fu_162_p2 == 2'd1) ? 1'b1 : 1'b0);

assign ones_1_fu_216_p2 = (add_ln71_2_fu_210_p2 + zext_ln71_3_fu_182_p1);

assign ones_2_fu_270_p2 = (add_ln71_4_fu_264_p2 + zext_ln71_6_fu_236_p1);

assign ones_fu_162_p2 = (add_ln71_fu_156_p2 + zext_ln71_1_fu_136_p1);

assign phi_ln61_fu_298_p3 = ((and_ln73_fu_294_p2[0:0] == 1'b1) ? phitmp_fu_287_p3 : 17'd0);

assign phitmp_fu_287_p3 = ((icmp_ln73_2_reg_340[0:0] == 1'b1) ? 17'd0 : 17'd70726);

assign sext_ln61_fu_306_p1 = $signed(phi_ln61_fu_298_p3);

assign state_im_address1 = zext_ln60_fu_119_p1;

assign state_im_ce1 = state_im_ce1_local;

assign state_im_d1 = 32'd0;

assign state_im_we1 = state_im_we1_local;

assign state_re_address1 = zext_ln60_reg_325;

assign state_re_ce1 = state_re_ce1_local;

assign state_re_d1 = zext_ln61_fu_310_p1;

assign state_re_we1 = state_re_we1_local;

assign tmp_93_fu_144_p3 = ap_sig_allocacmp_s_2[32'd2];

assign tmp_94_fu_174_p3 = ap_sig_allocacmp_s_2[32'd4];

assign tmp_95_fu_186_p3 = ap_sig_allocacmp_s_2[32'd3];

assign tmp_96_fu_198_p3 = ap_sig_allocacmp_s_2[32'd5];

assign tmp_97_fu_228_p3 = ap_sig_allocacmp_s_2[32'd7];

assign tmp_98_fu_240_p3 = ap_sig_allocacmp_s_2[32'd6];

assign tmp_99_fu_252_p3 = ap_sig_allocacmp_s_2[32'd8];

assign tmp_fu_128_p3 = ap_sig_allocacmp_s_2[32'd1];

assign trunc_ln103_fu_124_p1 = ap_sig_allocacmp_s_2[0:0];

assign zext_ln60_fu_119_p1 = ap_sig_allocacmp_s_2;

assign zext_ln61_fu_310_p1 = $unsigned(sext_ln61_fu_306_p1);

assign zext_ln71_1_fu_136_p1 = tmp_fu_128_p3;

assign zext_ln71_2_fu_152_p1 = tmp_93_fu_144_p3;

assign zext_ln71_3_fu_182_p1 = tmp_94_fu_174_p3;

assign zext_ln71_4_fu_194_p1 = tmp_95_fu_186_p3;

assign zext_ln71_5_fu_206_p1 = tmp_96_fu_198_p3;

assign zext_ln71_6_fu_236_p1 = tmp_97_fu_228_p3;

assign zext_ln71_7_fu_248_p1 = tmp_98_fu_240_p3;

assign zext_ln71_8_fu_260_p1 = tmp_99_fu_252_p3;

assign zext_ln71_fu_140_p1 = trunc_ln103_fu_124_p1;

always @ (posedge ap_clk) begin
    zext_ln60_reg_325[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //qaoa_kernel_build_feasible_superposition_3_s
