-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qaoa_kernel is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC );
end;


architecture behav of qaoa_kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "qaoa_kernel_qaoa_kernel,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=15.928667,HLS_SYN_LAT=182998,HLS_SYN_TPT=182998,HLS_SYN_MEM=18,HLS_SYN_DSP=0,HLS_SYN_FF=14394,HLS_SYN_LUT=29346,HLS_VERSION=2024_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal gamma : STD_LOGIC_VECTOR (31 downto 0);
    signal beta : STD_LOGIC_VECTOR (31 downto 0);
    signal get_best_state : STD_LOGIC_VECTOR (0 downto 0);
    signal d_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_entry_state_re_wr_d_rd_proc_U0_ap_start : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_ap_done : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_ap_continue : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_ap_idle : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_ap_ready : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_d_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Block_entry_state_re_wr_d_rd_proc_U0_d_ce0 : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_best_state : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_entry_state_re_wr_d_rd_proc_U0_best_state_ap_vld : STD_LOGIC;
    signal Block_entry_state_re_wr_d_rd_proc_U0_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_retval_0_loc_channel1 : STD_LOGIC;
    signal retval_0_loc_channel1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_retval_0_loc_channel1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_retval_0_loc_channel1 : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_start : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_done : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_continue : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_idle : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_ready : STD_LOGIC;
    signal Block_entry_proc_proc_U0_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_0_loc_channel1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_0_loc_channel1_empty_n : STD_LOGIC;
    signal retval_0_loc_channel1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal retval_0_loc_channel1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_done : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return : STD_LOGIC_VECTOR (31 downto 0);

    component qaoa_kernel_Block_entry_state_re_wr_d_rd_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        d_ce0 : OUT STD_LOGIC;
        d_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        gamma : IN STD_LOGIC_VECTOR (31 downto 0);
        beta : IN STD_LOGIC_VECTOR (31 downto 0);
        get_best_state : IN STD_LOGIC_VECTOR (0 downto 0);
        best_state : OUT STD_LOGIC_VECTOR (31 downto 0);
        best_state_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component qaoa_kernel_Block_entry_proc_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component qaoa_kernel_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component qaoa_kernel_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (31 downto 0);
        gamma : OUT STD_LOGIC_VECTOR (31 downto 0);
        beta : OUT STD_LOGIC_VECTOR (31 downto 0);
        get_best_state : OUT STD_LOGIC_VECTOR (0 downto 0);
        best_state : IN STD_LOGIC_VECTOR (31 downto 0);
        best_state_ap_vld : IN STD_LOGIC;
        d_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        d_ce0 : IN STD_LOGIC;
        d_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    control_s_axi_U : component qaoa_kernel_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => Block_entry_proc_proc_U0_ap_return,
        gamma => gamma,
        beta => beta,
        get_best_state => get_best_state,
        best_state => Block_entry_state_re_wr_d_rd_proc_U0_best_state,
        best_state_ap_vld => Block_entry_state_re_wr_d_rd_proc_U0_best_state_ap_vld,
        d_address0 => Block_entry_state_re_wr_d_rd_proc_U0_d_address0,
        d_ce0 => Block_entry_state_re_wr_d_rd_proc_U0_d_ce0,
        d_q0 => d_q0);

    Block_entry_state_re_wr_d_rd_proc_U0 : component qaoa_kernel_Block_entry_state_re_wr_d_rd_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry_state_re_wr_d_rd_proc_U0_ap_start,
        ap_done => Block_entry_state_re_wr_d_rd_proc_U0_ap_done,
        ap_continue => Block_entry_state_re_wr_d_rd_proc_U0_ap_continue,
        ap_idle => Block_entry_state_re_wr_d_rd_proc_U0_ap_idle,
        ap_ready => Block_entry_state_re_wr_d_rd_proc_U0_ap_ready,
        d_address0 => Block_entry_state_re_wr_d_rd_proc_U0_d_address0,
        d_ce0 => Block_entry_state_re_wr_d_rd_proc_U0_d_ce0,
        d_q0 => d_q0,
        gamma => gamma,
        beta => beta,
        get_best_state => get_best_state,
        best_state => Block_entry_state_re_wr_d_rd_proc_U0_best_state,
        best_state_ap_vld => Block_entry_state_re_wr_d_rd_proc_U0_best_state_ap_vld,
        ap_return => Block_entry_state_re_wr_d_rd_proc_U0_ap_return);

    Block_entry_proc_proc_U0 : component qaoa_kernel_Block_entry_proc_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry_proc_proc_U0_ap_start,
        ap_done => Block_entry_proc_proc_U0_ap_done,
        ap_continue => Block_entry_proc_proc_U0_ap_continue,
        ap_idle => Block_entry_proc_proc_U0_ap_idle,
        ap_ready => Block_entry_proc_proc_U0_ap_ready,
        p_read => retval_0_loc_channel1_dout,
        ap_return => Block_entry_proc_proc_U0_ap_return);

    retval_0_loc_channel1_U : component qaoa_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_entry_state_re_wr_d_rd_proc_U0_ap_return,
        if_full_n => retval_0_loc_channel1_full_n,
        if_write => ap_channel_done_retval_0_loc_channel1,
        if_dout => retval_0_loc_channel1_dout,
        if_empty_n => retval_0_loc_channel1_empty_n,
        if_read => Block_entry_proc_proc_U0_ap_ready,
        if_num_data_valid => retval_0_loc_channel1_num_data_valid,
        if_fifo_cap => retval_0_loc_channel1_fifo_cap);





    ap_sync_reg_channel_write_retval_0_loc_channel1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_retval_0_loc_channel1 <= ap_const_logic_0;
            else
                if (((Block_entry_state_re_wr_d_rd_proc_U0_ap_done and Block_entry_state_re_wr_d_rd_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_retval_0_loc_channel1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_retval_0_loc_channel1 <= ap_sync_channel_write_retval_0_loc_channel1;
                end if; 
            end if;
        end if;
    end process;

    Block_entry_proc_proc_U0_ap_continue <= ap_sync_done;
    Block_entry_proc_proc_U0_ap_start <= retval_0_loc_channel1_empty_n;
    Block_entry_state_re_wr_d_rd_proc_U0_ap_continue <= (ap_sync_continue and ap_sync_channel_write_retval_0_loc_channel1);
    Block_entry_state_re_wr_d_rd_proc_U0_ap_start <= ap_start;
    ap_channel_done_retval_0_loc_channel1 <= ((ap_sync_reg_channel_write_retval_0_loc_channel1 xor ap_const_logic_1) and Block_entry_state_re_wr_d_rd_proc_U0_ap_done);
    ap_done <= ap_sync_done;
    ap_idle <= ((retval_0_loc_channel1_empty_n xor ap_const_logic_1) and Block_entry_state_re_wr_d_rd_proc_U0_ap_idle and Block_entry_proc_proc_U0_ap_idle);
    ap_ready <= Block_entry_state_re_wr_d_rd_proc_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_channel_write_retval_0_loc_channel1 <= ((retval_0_loc_channel1_full_n and ap_channel_done_retval_0_loc_channel1) or ap_sync_reg_channel_write_retval_0_loc_channel1);
    ap_sync_continue <= ap_sync_done;
    ap_sync_done <= (Block_entry_state_re_wr_d_rd_proc_U0_ap_done and Block_entry_proc_proc_U0_ap_done);
end behav;
