// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln61,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [64:0] sext_ln61;
output  [64:0] p_out;
output   p_out_ap_vld;
output  [64:0] p_out1;
output   p_out1_ap_vld;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln61_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] circ_table_arctan_1289_address0;
wire   [125:0] circ_table_arctan_1289_q0;
wire    ap_block_pp0_stage0_11001;
reg   [65:0] p_load6_reg_298;
wire    ap_block_pp0_stage1_11001;
reg   [65:0] p_load_reg_304;
reg   [0:0] icmp_ln61_reg_310;
wire   [65:0] x_s_fu_165_p2;
reg   [65:0] x_s_reg_314;
wire   [65:0] y_s_fu_171_p2;
reg   [65:0] y_s_reg_320;
reg   [65:0] p_load7_reg_331;
wire   [0:0] d_fu_185_p3;
reg   [0:0] d_reg_337;
reg   [62:0] tmp_s_reg_342;
wire   [63:0] zext_ln61_fu_156_p1;
wire    ap_block_pp0_stage1;
reg   [65:0] empty_fu_52;
wire   [65:0] tz_fu_258_p3;
wire  signed [65:0] sext_ln61_cast_fu_101_p1;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [65:0] empty_55_fu_56;
wire   [65:0] tx_fu_219_p3;
reg   [65:0] empty_56_fu_60;
wire   [65:0] ty_fu_227_p3;
reg   [6:0] n_fu_64;
wire   [6:0] add_ln61_fu_150_p2;
wire    ap_block_pp0_stage1_01001;
reg    circ_table_arctan_1289_ce0_local;
wire   [65:0] zext_ln71_fu_161_p1;
wire   [65:0] add_ln76_fu_203_p2;
wire   [65:0] sub_ln81_fu_211_p2;
wire   [65:0] sub_ln77_fu_207_p2;
wire   [65:0] add_ln82_fu_215_p2;
wire   [65:0] zext_ln73_fu_245_p1;
wire   [65:0] add_ln78_fu_248_p2;
wire   [65:0] sub_ln83_fu_253_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 empty_fu_52 = 66'd0;
#0 empty_55_fu_56 = 66'd0;
#0 empty_56_fu_60 = 66'd0;
#0 n_fu_64 = 7'd0;
#0 ap_done_reg = 1'b0;
end

qaoa_kernel_applyCost_hls_3_s_cordic_apfixed_circ_table_arctan_128_ROM_AUTO_1R #(
    .DataWidth( 126 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
circ_table_arctan_1289_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(circ_table_arctan_1289_address0),
    .ce0(circ_table_arctan_1289_ce0_local),
    .q0(circ_table_arctan_1289_q0)
);

qaoa_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_55_fu_56 <= 66'd5600919740058903545;
        end else if (((icmp_ln61_reg_310 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_55_fu_56 <= tx_fu_219_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_56_fu_60 <= 66'd0;
        end else if (((icmp_ln61_reg_310 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_56_fu_60 <= ty_fu_227_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_fu_52 <= sext_ln61_cast_fu_101_p1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_fu_52 <= tz_fu_258_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        n_fu_64 <= 7'd0;
    end else if (((icmp_ln61_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        n_fu_64 <= add_ln61_fu_150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_reg_337 <= empty_fu_52[32'd65];
        p_load7_reg_331 <= empty_fu_52;
        tmp_s_reg_342 <= {{circ_table_arctan_1289_q0[125:63]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln61_reg_310 <= icmp_ln61_fu_144_p2;
        p_load6_reg_298 <= empty_55_fu_56;
        p_load_reg_304 <= empty_56_fu_60;
        x_s_reg_314 <= x_s_fu_165_p2;
        y_s_reg_320 <= y_s_fu_171_p2;
    end
end

always @ (*) begin
    if (((icmp_ln61_fu_144_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        circ_table_arctan_1289_ce0_local = 1'b1;
    end else begin
        circ_table_arctan_1289_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln61_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln61_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln61_fu_150_p2 = (n_fu_64 + 7'd1);

assign add_ln76_fu_203_p2 = (p_load6_reg_298 + y_s_reg_320);

assign add_ln78_fu_248_p2 = (zext_ln73_fu_245_p1 + p_load7_reg_331);

assign add_ln82_fu_215_p2 = (x_s_reg_314 + p_load_reg_304);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign circ_table_arctan_1289_address0 = zext_ln61_fu_156_p1;

assign d_fu_185_p3 = empty_fu_52[32'd65];

assign icmp_ln61_fu_144_p2 = ((n_fu_64 == 7'd66) ? 1'b1 : 1'b0);

assign p_out = empty_56_fu_60[64:0];

assign p_out1 = empty_55_fu_56[64:0];

assign sext_ln61_cast_fu_101_p1 = $signed(sext_ln61);

assign sub_ln77_fu_207_p2 = (p_load_reg_304 - x_s_reg_314);

assign sub_ln81_fu_211_p2 = (p_load6_reg_298 - y_s_reg_320);

assign sub_ln83_fu_253_p2 = (p_load7_reg_331 - zext_ln73_fu_245_p1);

assign tx_fu_219_p3 = ((d_fu_185_p3[0:0] == 1'b1) ? add_ln76_fu_203_p2 : sub_ln81_fu_211_p2);

assign ty_fu_227_p3 = ((d_fu_185_p3[0:0] == 1'b1) ? sub_ln77_fu_207_p2 : add_ln82_fu_215_p2);

assign tz_fu_258_p3 = ((d_reg_337[0:0] == 1'b1) ? add_ln78_fu_248_p2 : sub_ln83_fu_253_p2);

assign x_s_fu_165_p2 = $signed(empty_55_fu_56) >>> zext_ln71_fu_161_p1;

assign y_s_fu_171_p2 = $signed(empty_56_fu_60) >>> zext_ln71_fu_161_p1;

assign zext_ln61_fu_156_p1 = n_fu_64;

assign zext_ln71_fu_161_p1 = n_fu_64;

assign zext_ln73_fu_245_p1 = tmp_s_reg_342;

endmodule //qaoa_kernel_applyMixer_hls_3_Pipeline_VITIS_LOOP_61_1
